# Improving Merge

Merging IMDB Core with ticket sales data has to rely on title and year match. 
After we fixed issues with movies being released in the same year under the same title, we faced a new one. 
<br><br>
There are numerous titles with slightly different names. 
Roughly 1k per data set don't match. 
<br><br>
Next goal is to analyze the mismatch and correct that. 

### 1. Importing packages and data from sql

In [1]:
import pandas as pd
import numpy as np
import psycopg2 as psycopg2
import sql_functions as sqlf

In [2]:
schema = "capstone_24_4_group1"
schema

'capstone_24_4_group1'

In [3]:
imdb_query = f'''   SELECT *
                    FROM {schema}."IMDB_data"
                    '''

eu_query = f'''   SELECT *
                    FROM {schema}."movie_data_EU"
                    '''

na_query = f'''   SELECT *
                    FROM {schema}."movie_data_NA"
                    '''

In [4]:
imdb_df = sqlf.get_dataframe(imdb_query)
display(imdb_df.head())
imdb_df.shape

tconst                                      primary_title  \
0  tt0013274                        Istoriya grazhdanskoy voyny   
1  tt0015414                             La tierra de los toros   
2  tt0035423                                     Kate & Leopold   
3  tt0062336  The Tango of the Widower and Its Distorting Mi...   
4  tt0069049                         The Other Side of the Wind   

                              original_title  year runtime  num_votes  \
0                Istoriya grazhdanskoy voyny  2021      94       73.0   
1                     La tierra de los toros  2000      60       17.0   
2                             Kate & Leopold  2001     118    89944.0   
3  El tango del viudo y su espejo deformante  2020      70      190.0   
4                 The Other Side of the Wind  2018     122     8143.0   

   average_rating  genres_count        genre   genre2  ...         acting5  \
0             6.7           1.0  Documentary     None  ...            None   
1             5.4           NaN         None     None  ...            None   
2             6.4           3.0       Comedy  Fantasy  ...  Natasha Lyonne   
3             6.5           1.0        Drama     None  ...    Luis Vilches   
4             6.7           1.0        Drama     None  ...   Norman Foster   

  directors_count    director_name     director2_name director3_name  \
0             2.0  Nikolai Izvolov       Dziga Vertov           None   
1             1.0         Musidora               None           None   
2             1.0    James Mangold               None           None   
3             2.0        Raúl Ruiz  Valeria Sarmiento           None   
4             1.0     Orson Welles               None           None   

  writers_count    writer_name          writer2_name writer3_name is_adult  
0           NaN           None                  None         None        0  
1           NaN           None                  None         None        0  
2           2.0  Steven Rogers         James Mangold         None        0  
3           2.0      Raúl Ruiz  Omar Saavedra Santis         None        0  
4           2.0   Orson Welles             Oja Kodar         None        0  

[5 rows x 25 columns]

(188163, 25)

In [5]:
eu_df = sqlf.get_dataframe(eu_query)
display(eu_df.head())
eu_df.shape

title producing_country  year  \
0                               (500) Days of Summer                US  2009   
1                                       (Nie)znajomi                PL  2019   
2                 (T)Raumschiff Surprise - Periode 1                DE  2004   
3  1 1/2 Ritter - Auf der Suche nach der hinreiße...                DE  2008   
4                                     1 chance sur 2                FR  1998   

   tickets_sold_since_1996  tickets_sold  
0                  1713086       1684771  
1                   685075        684833  
2                 10763531      10731881  
3                  1986168       1986168  
4                  1295620       1238175

(4956, 5)

In [6]:
na_df = sqlf.get_dataframe(na_query)
display(na_df.head())
na_df.shape

title release_date         distributor  gross_sales  \
0        (500) Days of Summer   2009-08-07     Fox Searchlight     32425665   
1         10 Cloverfield Lane   2016-03-11  Paramount Pictures     72082999   
2  10 Things I Hate About You   1999-03-31         Walt Disney     38177966   
3                 10,000 B.C.   2008-03-07        Warner Bros.     94784201   
4              101 Dalmatians   1996-11-27         Walt Disney    136189294   

   tickets_sold  release_year  
0       4323422          2009  
1       8333294          2016  
2       7515347          1999  
3      13201142          2008  
4      30691447          1996

(4965, 6)

## 2. Get not matching movies
### EU

In [7]:
eu_unmatched_df = pd.merge(eu_df,imdb_df, how="left", left_on=["title", "year"], right_on=["original_title", "year"])
eu_unmatched_df.shape

(4959, 29)

In [8]:
eu_unmatched_mask = eu_unmatched_df["tconst"].isnull()

In [9]:
eu_unmatched_df[eu_unmatched_mask]

title producing_country  year  \
13                  101 Dalmatians                US  1996   
20                  13 Going On 30                US  2004   
22    15 Minutes (Fifteen Minutes)                US  2001   
41                              23                DE  1998   
47                   28 Days Later                GB  2002   
...                            ...               ...   ...   
4949   Çok filim hareketler bunlar                TR  2010   
4955             Účastníci zájezdu                CZ  2006   
4956              Śluby panieńskie                PL  2010   
4957                    Świadectwo                PL  2008   
4958               Ženy v pokušení                CZ  2010   

      tickets_sold_since_1996  tickets_sold tconst primary_title  \
13                   21623260      21532085    NaN           NaN   
20                    3579724       3566771    NaN           NaN   
22                    2600419       2565397    NaN           NaN   
41                     701787        693358    NaN           NaN   
47                    4252690       4066710    NaN           NaN   
...                       ...           ...    ...           ...   
4949                  1223552       1223156    NaN           NaN   
4955                   871439        830242    NaN           NaN   
4956                  1001866       1000373    NaN           NaN   
4957                  1039901       1034911    NaN           NaN   
4958                  1309118       1303914    NaN           NaN   

     original_title runtime  num_votes  ...  acting5  directors_count  \
13              NaN     NaN        NaN  ...      NaN              NaN   
20              NaN     NaN        NaN  ...      NaN              NaN   
22              NaN     NaN        NaN  ...      NaN              NaN   
41              NaN     NaN        NaN  ...      NaN              NaN   
47              NaN     NaN        NaN  ...      NaN              NaN   
...             ...     ...        ...  ...      ...              ...   
4949            NaN     NaN        NaN  ...      NaN              NaN   
4955            NaN     NaN        NaN  ...      NaN              NaN   
4956            NaN     NaN        NaN  ...      NaN              NaN   
4957            NaN     NaN        NaN  ...      NaN              NaN   
4958            NaN     NaN        NaN  ...      NaN              NaN   

     director_name director2_name director3_name writers_count writer_name  \
13             NaN            NaN            NaN           NaN         NaN   
20             NaN            NaN            NaN           NaN         NaN   
22             NaN            NaN            NaN           NaN         NaN   
41             NaN            NaN            NaN           NaN         NaN   
47             NaN            NaN            NaN           NaN         NaN   
...            ...            ...            ...           ...         ...   
4949           NaN            NaN            NaN           NaN         NaN   
4955           NaN            NaN            NaN           NaN         NaN   
4956           NaN            NaN            NaN           NaN         NaN   
4957           NaN            NaN            NaN           NaN         NaN   
4958           NaN            NaN            NaN           NaN         NaN   

     writer2_name writer3_name is_adult  
13            NaN          NaN      NaN  
20            NaN          NaN      NaN  
22            NaN          NaN      NaN  
41            NaN          NaN      NaN  
47            NaN          NaN      NaN  
...           ...          ...      ...  
4949          NaN          NaN      NaN  
4955          NaN          NaN      NaN  
4956          NaN          NaN      NaN  
4957          NaN          NaN      NaN  
4958          NaN          NaN      NaN  

[775 rows x 29 columns]

currently 922 unmatched rows

### Let's check how much lower case improves (add for EU and NA)

In [10]:
imdb_df["original_title_merge"] = imdb_df["original_title"].str.lower()
eu_df["title_merge"] = eu_df["title"].str.lower()
na_df["title_merge"] = na_df["title"].str.lower()
display(imdb_df.head())
display(eu_df.head())
display(na_df.head())

tconst                                      primary_title  \
0  tt0013274                        Istoriya grazhdanskoy voyny   
1  tt0015414                             La tierra de los toros   
2  tt0035423                                     Kate & Leopold   
3  tt0062336  The Tango of the Widower and Its Distorting Mi...   
4  tt0069049                         The Other Side of the Wind   

                              original_title  year runtime  num_votes  \
0                Istoriya grazhdanskoy voyny  2021      94       73.0   
1                     La tierra de los toros  2000      60       17.0   
2                             Kate & Leopold  2001     118    89944.0   
3  El tango del viudo y su espejo deformante  2020      70      190.0   
4                 The Other Side of the Wind  2018     122     8143.0   

   average_rating  genres_count        genre   genre2  ... directors_count  \
0             6.7           1.0  Documentary     None  ...             2.0   
1             5.4           NaN         None     None  ...             1.0   
2             6.4           3.0       Comedy  Fantasy  ...             1.0   
3             6.5           1.0        Drama     None  ...             2.0   
4             6.7           1.0        Drama     None  ...             1.0   

     director_name     director2_name director3_name writers_count  \
0  Nikolai Izvolov       Dziga Vertov           None           NaN   
1         Musidora               None           None           NaN   
2    James Mangold               None           None           2.0   
3        Raúl Ruiz  Valeria Sarmiento           None           2.0   
4     Orson Welles               None           None           2.0   

     writer_name          writer2_name writer3_name is_adult  \
0           None                  None         None        0   
1           None                  None         None        0   
2  Steven Rogers         James Mangold         None        0   
3      Raúl Ruiz  Omar Saavedra Santis         None        0   
4   Orson Welles             Oja Kodar         None        0   

                        original_title_merge  
0                istoriya grazhdanskoy voyny  
1                     la tierra de los toros  
2                             kate & leopold  
3  el tango del viudo y su espejo deformante  
4                 the other side of the wind  

[5 rows x 26 columns]

title producing_country  year  \
0                               (500) Days of Summer                US  2009   
1                                       (Nie)znajomi                PL  2019   
2                 (T)Raumschiff Surprise - Periode 1                DE  2004   
3  1 1/2 Ritter - Auf der Suche nach der hinreiße...                DE  2008   
4                                     1 chance sur 2                FR  1998   

   tickets_sold_since_1996  tickets_sold  \
0                  1713086       1684771   
1                   685075        684833   
2                 10763531      10731881   
3                  1986168       1986168   
4                  1295620       1238175   

                                         title_merge  
0                               (500) days of summer  
1                                       (nie)znajomi  
2                 (t)raumschiff surprise - periode 1  
3  1 1/2 ritter - auf der suche nach der hinreiße...  
4                                     1 chance sur 2

title release_date         distributor  gross_sales  \
0        (500) Days of Summer   2009-08-07     Fox Searchlight     32425665   
1         10 Cloverfield Lane   2016-03-11  Paramount Pictures     72082999   
2  10 Things I Hate About You   1999-03-31         Walt Disney     38177966   
3                 10,000 B.C.   2008-03-07        Warner Bros.     94784201   
4              101 Dalmatians   1996-11-27         Walt Disney    136189294   

   tickets_sold  release_year                 title_merge  
0       4323422          2009        (500) days of summer  
1       8333294          2016         10 cloverfield lane  
2       7515347          1999  10 things i hate about you  
3      13201142          2008                 10,000 b.c.  
4      30691447          1996              101 dalmatians

In [11]:
eu_check_df = pd.merge(eu_df,imdb_df, how="left", left_on=["title_merge", "year"], right_on=["original_title_merge", "year"])

In [12]:
eu_check_mask = eu_check_df["tconst"].isnull()
eu_check_df[eu_check_mask]

title producing_country  year  \
13                   101 Dalmatians                US  1996   
22     15 Minutes (Fifteen Minutes)                US  2001   
41                               23                DE  1998   
47                    28 Days Later                GB  2002   
59    4 luni, 3 saptamani si 2 zile                RO  2007   
...                             ...               ...   ...   
4930                        [Rec] 2                ES  2009   
4955              Účastníci zájezdu                CZ  2006   
4956               Śluby panieńskie                PL  2010   
4957                     Świadectwo                PL  2008   
4958                Ženy v pokušení                CZ  2010   

      tickets_sold_since_1996  tickets_sold                    title_merge  \
13                   21623260      21532085                 101 dalmatians   
22                    2600419       2565397   15 minutes (fifteen minutes)   
41                     701787        693358                             23   
47                    4252690       4066710                  28 days later   
59                    1090696        736957  4 luni, 3 saptamani si 2 zile   
...                       ...           ...                            ...   
4930                  1387671       1013091                        [rec] 2   
4955                   871439        830242              účastníci zájezdu   
4956                  1001866       1000373               śluby panieńskie   
4957                  1039901       1034911                     świadectwo   
4958                  1309118       1303914                ženy v pokušení   

     tconst primary_title original_title runtime  ...  directors_count  \
13      NaN           NaN            NaN     NaN  ...              NaN   
22      NaN           NaN            NaN     NaN  ...              NaN   
41      NaN           NaN            NaN     NaN  ...              NaN   
47      NaN           NaN            NaN     NaN  ...              NaN   
59      NaN           NaN            NaN     NaN  ...              NaN   
...     ...           ...            ...     ...  ...              ...   
4930    NaN           NaN            NaN     NaN  ...              NaN   
4955    NaN           NaN            NaN     NaN  ...              NaN   
4956    NaN           NaN            NaN     NaN  ...              NaN   
4957    NaN           NaN            NaN     NaN  ...              NaN   
4958    NaN           NaN            NaN     NaN  ...              NaN   

      director_name  director2_name director3_name writers_count writer_name  \
13              NaN             NaN            NaN           NaN         NaN   
22              NaN             NaN            NaN           NaN         NaN   
41              NaN             NaN            NaN           NaN         NaN   
47              NaN             NaN            NaN           NaN         NaN   
59              NaN             NaN            NaN           NaN         NaN   
...             ...             ...            ...           ...         ...   
4930            NaN             NaN            NaN           NaN         NaN   
4955            NaN             NaN            NaN           NaN         NaN   
4956            NaN             NaN            NaN           NaN         NaN   
4957            NaN             NaN            NaN           NaN         NaN   
4958            NaN             NaN            NaN           NaN         NaN   

     writer2_name writer3_name is_adult original_title_merge  
13            NaN          NaN      NaN                  NaN  
22            NaN          NaN      NaN                  NaN  
41            NaN          NaN      NaN                  NaN  
47            NaN          NaN      NaN                  NaN  
59            NaN          NaN      NaN                  NaN  
...           ...          ...      ...                  ...  
4930          NaN          NaN      NaN      

From 922 to 788 unmatched rows
-> 134 less problems

### Check what's wrong with "101 Dalmatians"

In [13]:
imdb_df[imdb_df["tconst"] == "tt0115433"]

Empty DataFrame
Columns: [tconst, primary_title, original_title, year, runtime, num_votes, average_rating, genres_count, genre, genre2, genre3, acting, acting2, acting3, acting4, acting5, directors_count, director_name, director2_name, director3_name, writers_count, writer_name, writer2_name, writer3_name, is_adult, original_title_merge]
Index: []

[0 rows x 26 columns]

hmm ... can't find the 101 ... movie ... why? 

In [14]:
imdb_df[imdb_df["original_title"].str.contains("101")].sort_values(by="original_title").head(15)

tconst                                      primary_title  \
136405   tt3668280                                   101 Chodhyangal?   
145785   tt4512212        101 Reasons: Liberty Lives in New Hampshire   
9269     tt0252802                                      101 Rent Boys   
8196     tt0237993                                      101 Reykjavík   
69922   tt14358208                                           101 Reys   
185698   tt9429520                                        101 Seconds   
130417   tt3219396                                        101 Secrets   
8418     tt0241142  101 Ways (the Things a Girl Will Do to Keep He...   
115606   tt2545176                                       101 Weddings   
84889    tt1674766                                      101 Proposals   
12346    tt0289041                                    101st Kilometer   
140709   tt4034426                                               1010   
77681    tt1541061                                    1013 Briar Lane   
135955   tt3627828                   101: Modern Los Angeles Vampires   
126949   tt3004572                                               2101   

                                           original_title  year runtime  \
136405                                   101 Chodhyangal?  2013     107   
145785        101 Reasons: Liberty Lives in New Hampshire  2014      64   
9269                                        101 Rent Boys  2000      78   
8196                                        101 Reykjavík  2000      88   
69922                                            101 Reys  2020     110   
185698                                        101 Seconds  2018      81   
130417                                        101 Secrets  2015      95   
8418    101 Ways (The Things a Girl Will Do to Keep He...  2000     100   
115606                                       101 Weddings  2012     145   
84889                                      101 ci qiu hun  2013     120   
12346                                      101-y kilometr  2001     103   
140709                                               1010  2014      50   
77681                                     1013 Briar Lane  2009      83   
135955                   101: Modern Los Angeles Vampires  2014      78   
126949                                               2101  2014      56   

        num_votes  average_rating  genres_count        genre     genre2  ...  \
136405      113.0             7.0           2.0        Drama     Family  ...   
145785       14.0             8.6           2.0  Documentary       News  ...   
9269        384.0             6.5           1.0  Documentary       None  ...   
8196       9967.0             6.8           3.0       Comedy      Drama  ...   
69922        20.0             7.8           1.0    Biography       None  ...   
185698       29.0             6.2           1.0  Documentary       None  ...   
130417       15.0             5.3           3.0    Adventure      Drama  ...   
8418        162.0             5.2           1.0       Comedy       None  ...   
115606      235.0             4.7           3.0       Comedy      Drama  ...   
84889       526.0             5.4           1.0      Romance       None  ...   
12346        56.0             6.8           1.0        Drama       None  ...   
140709       17.0             7.1           1.0        Drama       None  ...   
77681        16.0             6.7           2.0  Documentary     Horror  ...   
135955       35.0             3.4           1.0       Horror       None  ...   
126949      379.0             2.2           3.0       Action  Adventure  ...   

       directors_count      director_name director2_name director3_name  \
136405             1.0     Sidhartha Siva           None           None   
145785             1.0         Beau Davis           None           None   
9269               2.0      Fenton Bailey  Randy Barbato           None   
8196               1.0  Baltasar Kormákur           None     

### Check if we can find the tconst in the basic data-set

In [15]:
basic_df = pd.read_csv("Data/title.principals/title.basics.csv")
basic_df.shape

(11057208, 9)

In [16]:
basic_df[basic_df["tconst"] == "tt0115433"]

tconst titleType    primaryTitle   originalTitle  isAdult  \
112776  tt0115433     movie  101 Dalmatians  101 Dalmatians      0.0   

        startYear endYear runtimeMinutes                  genres  
112776     1996.0      \N            103  Adventure,Comedy,Crime

Is is in there ... that means we drop it unwanted at some stage during the filtering process <br><br>

First idea: Maybe we filter for year > 1996 instead of year >= 1996?

### Solution: 

It is the other way round. We decided to look at the last 25 years (1998-2023) and filtered the IMDB data accordingly. However, the EU and NA data starts at 1996. Those we never filtered for the appropriate date range ... 

Let's correct this ... 

### Filter EU and NA for Year >= 1998

In [17]:
eu_df[eu_df["year"] >= 1998].sort_values(by="year")

title   producing_country  year  \
770                 City of Angels                  US  1998   
992             Desperate Measures                  US  1998   
3413                     Rush Hour                  US  1998   
2251                       Lautrec              FR, ES  1998   
4748                         Virus  US, GB, JP, DE, FR  1998   
...                            ...                 ...   ...   
97            A Haunting in Venice                  US  2023   
3858                  Thanksgiving          US, CA, AU  2023   
2967  O psie, który jezdzil koleja                  PL  2023   
3828   Taylor Swift: The Eras Tour                  US  2023   
3402  Ruby Gillman, Teenage Kraken              US, JP  2023   

      tickets_sold_since_1996  tickets_sold                   title_merge  
770                   8318763       8271916                city of angels  
992                   1194818       1191026            desperate measures  
3413                  8120318       8007449                     rush hour  
2251                   650948        560307                       lautrec  
4748                  1719742       1715116                         virus  
...                       ...           ...                           ...  
97                    6170413       6170413          a haunting in venice  
3858                  1006977       1006977                  thanksgiving  
2967                   730994        730994  o psie, który jezdzil koleja  
3828                  2120352       2120352   taylor swift: the eras tour  
3402                  2114278       2114278  ruby gillman, teenage kraken  

[4541 rows x 6 columns]

In [18]:
eu_df = eu_df[eu_df["year"] >= 1998].reset_index(drop=True)
eu_df

title producing_country  \
0                                  (500) Days of Summer                US   
1                                          (Nie)znajomi                PL   
2                    (T)Raumschiff Surprise - Periode 1                DE   
3     1 1/2 Ritter - Auf der Suche nach der hinreiße...                DE   
4                                        1 chance sur 2                FR   
...                                                 ...               ...   
4536                                     Ölümlü Dünya 2                TR   
4537                                  Účastníci zájezdu                CZ   
4538                                   Śluby panieńskie                PL   
4539                                         Świadectwo                PL   
4540                                    Ženy v pokušení                CZ   

      year  tickets_sold_since_1996  tickets_sold  \
0     2009                  1713086       1684771   
1     2019                   685075        684833   
2     2004                 10763531      10731881   
3     2008                  1986168       1986168   
4     1998                  1295620       1238175   
...    ...                      ...           ...   
4536  2023                  1476943       1476943   
4537  2006                   871439        830242   
4538  2010                  1001866       1000373   
4539  2008                  1039901       1034911   
4540  2010                  1309118       1303914   

                                            title_merge  
0                                  (500) days of summer  
1                                          (nie)znajomi  
2                    (t)raumschiff surprise - periode 1  
3     1 1/2 ritter - auf der suche nach der hinreiße...  
4                                        1 chance sur 2  
...                                                 ...  
4536                                     ölümlü dünya 2  
4537                                  účastníci zájezdu  
4538                                   śluby panieńskie  
4539                                         świadectwo  
4540                                    ženy v pokušení  

[4541 rows x 6 columns]

In [19]:
na_df[na_df["release_year"] >= 1998].sort_values(by="release_year")


title release_date           distributor  \
2214              Little Voice   1998-12-04               Miramax   
1688         Hilary and Jackie   1998-12-30         October Films   
406      Babe: Pig in the City   1998-11-25             Universal   
4107  The Man in the Iron Mask   1998-03-13                   MGM   
989                Deep Impact   1998-05-08    Paramount Pictures   
...                        ...          ...                   ...   
2714               Oppenheimer   2023-07-21             Universal   
4758     Waitress: The Musical   2023-12-07       Bleecker Street   
593                Blue Beetle   2023-08-18          Warner Bros.   
4116               The Marvels   2023-11-10           Walt Disney   
2501                 Moving On   2023-03-17  Roadside Attractions   

      gross_sales  tickets_sold  release_year               title_merge  
2214      3714954        731290          1998              little voice  
1688      4739909        933052          1998         hilary and jackie  
406      18319860       3870373          1998     babe: pig in the city  
4107     56968169      12146731          1998  the man in the iron mask  
989     140464664      29949821          1998               deep impact  
...           ...           ...           ...                       ...  
2714    326101370      30250590          2023               oppenheimer  
4758      5402148        501126          2023     waitress: the musical  
593      72541501       6729267          2023               blue beetle  
4116     84479155       7836656          2023               the marvels  
2501      2136832        198221          2023                 moving on  

[4544 rows x 7 columns]

In [20]:
na_df = na_df[na_df["release_year"] >= 1998].reset_index(drop=True)
na_df

title release_date         distributor  \
0           (500) Days of Summer   2009-08-07     Fox Searchlight   
1            10 Cloverfield Lane   2016-03-11  Paramount Pictures   
2     10 Things I Hate About You   1999-03-31         Walt Disney   
3                    10,000 B.C.   2008-03-07        Warner Bros.   
4                 102 Dalmatians   2000-11-22         Walt Disney   
...                          ...          ...                 ...   
4539                       earth   2009-04-22         Walt Disney   
4540             jackass forever   2022-02-04  Paramount Pictures   
4541                     mother!   2017-09-15  Paramount Pictures   
4542                         xXx   2002-08-09       Sony Pictures   
4543  xXx: Return of Xander Cage   2017-01-20  Paramount Pictures   

      gross_sales  tickets_sold  release_year                 title_merge  
0        32425665       4323422          2009        (500) days of summer  
1        72082999       8333294          2016         10 cloverfield lane  
2        38177966       7515347          1999  10 things i hate about you  
3        94784201      13201142          2008                 10,000 b.c.  
4        66941559      12343421          2000              102 dalmatians  
...           ...           ...           ...                         ...  
4539     32011576       4268210          2009                       earth  
4540     57743451       5483709          2022             jackass forever  
4541     17800004       1984392          2017                     mother!  
4542    141930000      24428571          2002                         xxx  
4543     44898413       5005397          2017  xxx: return of xander cage  

[4544 rows x 7 columns]

### Check Merge with reducced EU Data (4541 rows)

In [21]:
eu_check_df = pd.merge(eu_df,imdb_df, how="left", left_on=["title_merge", "year"], right_on=["original_title_merge", "year"])

In [22]:
eu_check_mask = eu_check_df["tconst"].isnull()
eu_check_df[eu_check_mask]

title producing_country  year  \
21     15 Minutes (Fifteen Minutes)                US  2001   
40                               23                DE  1998   
46                    28 Days Later                GB  2002   
58    4 luni, 3 saptamani si 2 zile                RO  2007   
65               5X2 cinq fois deux                FR  2004   
...                             ...               ...   ...   
4515                        [Rec] 2                ES  2009   
4540              Účastníci zájezdu                CZ  2006   
4541               Śluby panieńskie                PL  2010   
4542                     Świadectwo                PL  2008   
4543                Ženy v pokušení                CZ  2010   

      tickets_sold_since_1996  tickets_sold                    title_merge  \
21                    2600419       2565397   15 minutes (fifteen minutes)   
40                     701787        693358                             23   
46                    4252690       4066710                  28 days later   
58                    1090696        736957  4 luni, 3 saptamani si 2 zile   
65                    1150178        814942             5x2 cinq fois deux   
...                       ...           ...                            ...   
4515                  1387671       1013091                        [rec] 2   
4540                   871439        830242              účastníci zájezdu   
4541                  1001866       1000373               śluby panieńskie   
4542                  1039901       1034911                     świadectwo   
4543                  1309118       1303914                ženy v pokušení   

     tconst primary_title original_title runtime  ...  directors_count  \
21      NaN           NaN            NaN     NaN  ...              NaN   
40      NaN           NaN            NaN     NaN  ...              NaN   
46      NaN           NaN            NaN     NaN  ...              NaN   
58      NaN           NaN            NaN     NaN  ...              NaN   
65      NaN           NaN            NaN     NaN  ...              NaN   
...     ...           ...            ...     ...  ...              ...   
4515    NaN           NaN            NaN     NaN  ...              NaN   
4540    NaN           NaN            NaN     NaN  ...              NaN   
4541    NaN           NaN            NaN     NaN  ...              NaN   
4542    NaN           NaN            NaN     NaN  ...              NaN   
4543    NaN           NaN            NaN     NaN  ...              NaN   

      director_name  director2_name director3_name writers_count writer_name  \
21              NaN             NaN            NaN           NaN         NaN   
40              NaN             NaN            NaN           NaN         NaN   
46              NaN             NaN            NaN           NaN         NaN   
58              NaN             NaN            NaN           NaN         NaN   
65              NaN             NaN            NaN           NaN         NaN   
...             ...             ...            ...           ...         ...   
4515            NaN             NaN            NaN           NaN         NaN   
4540            NaN             NaN            NaN           NaN         NaN   
4541            NaN             NaN            NaN           NaN         NaN   
4542            NaN             NaN            NaN           NaN         NaN   
4543            NaN             NaN            NaN           NaN         NaN   

     writer2_name writer3_name is_adult original_title_merge  
21            NaN          NaN      NaN                  NaN  
40            NaN          NaN      NaN                  NaN  
46            NaN          NaN      NaN                  NaN  
58            NaN          NaN      NaN                  NaN  
65            NaN          NaN      NaN                  NaN  
...           ...          ...      ...                  ...  
4515          NaN          NaN      NaN      

We are down to 373 unmatched rows (from 788)
-> improved by 415

### Check Problem with 15Minutes

In [23]:
imdb_df[imdb_df["tconst"] == "tt0179626"]

tconst primary_title original_title  year runtime  num_votes  \
4855  tt0179626    15 Minutes     15 Minutes  2001     120    52238.0   

      average_rating  genres_count   genre genre2  ... directors_count  \
4855             6.1           3.0  Action  Crime  ...             1.0   

      director_name director2_name director3_name writers_count  \
4855  John Herzfeld           None           None           1.0   

        writer_name  writer2_name writer3_name is_adult original_title_merge  
4855  John Herzfeld          None         None        0           15 minutes  

[1 rows x 26 columns]

ok the EU data contains the numbers written out in brackets. The IMDB does not. <br> <br>

Does that happen for other movies, too? 

In [24]:
bracket_mask = eu_check_df["title_merge"].str.contains("\(")
eu_check_df[eu_check_mask & bracket_mask]

title producing_country  \
21                         15 Minutes (Fifteen Minutes)                US   
411                                          Beast (US)        US, IS, JP   
812   Dangerous Beauty (The Honest Courtesan, A Dest...                US   
2809                                     Paparazzi (FR)                FR   
2810                                     Paparazzi (IT)                IT   

      year  tickets_sold_since_1996  tickets_sold  \
21    2001                  2600419       2565397   
411   2022                  1078911       1078729   
812   1998                   929520        928888   
2809  1998                   994869        988887   
2810  1998                  1604573       1604573   

                                            title_merge tconst primary_title  \
21                         15 minutes (fifteen minutes)    NaN           NaN   
411                                          beast (us)    NaN           NaN   
812   dangerous beauty (the honest courtesan, a dest...    NaN           NaN   
2809                                     paparazzi (fr)    NaN           NaN   
2810                                     paparazzi (it)    NaN           NaN   

     original_title runtime  ...  directors_count  director_name  \
21              NaN     NaN  ...              NaN            NaN   
411             NaN     NaN  ...              NaN            NaN   
812             NaN     NaN  ...              NaN            NaN   
2809            NaN     NaN  ...              NaN            NaN   
2810            NaN     NaN  ...              NaN            NaN   

      director2_name director3_name writers_count writer_name writer2_name  \
21               NaN            NaN           NaN         NaN          NaN   
411              NaN            NaN           NaN         NaN          NaN   
812              NaN            NaN           NaN         NaN          NaN   
2809             NaN            NaN           NaN         NaN          NaN   
2810             NaN            NaN           NaN         NaN          NaN   

     writer3_name is_adult original_title_merge  
21            NaN      NaN                  NaN  
411           NaN      NaN                  NaN  
812           NaN      NaN                  NaN  
2809          NaN      NaN                  NaN  
2810          NaN      NaN                  NaN  

[5 rows x 31 columns]

Nop, unique problem ... but Paparazzi also does not match!! <br><br>

Anyway ... Correct 15 Minutes first

In [25]:
eu_df.loc[eu_df["title_merge"] == "15 minutes (fifteen minutes)", "title_merge"]

21    15 minutes (fifteen minutes)
Name: title_merge, dtype: object

In [26]:
eu_df.loc[eu_df["title_merge"] == "15 minutes (fifteen minutes)", "title_merge"] = "15 minutes"
eu_df.loc[eu_df["title_merge"] == "15 minutes"]

title producing_country  year  \
21  15 Minutes (Fifteen Minutes)                US  2001   

    tickets_sold_since_1996  tickets_sold title_merge  
21                  2600419       2565397  15 minutes

### repeat with new eu_df and check out Paparazzi problems

In [27]:
eu_check_df = pd.merge(eu_df,imdb_df, how="left", left_on=["title_merge", "year"], right_on=["original_title_merge", "year"])

In [28]:
eu_check_mask = eu_check_df["tconst"].isnull()
eu_check_df[eu_check_mask]

title producing_country  year  \
40                                        23                DE  1998   
46                             28 Days Later                GB  2002   
58             4 luni, 3 saptamani si 2 zile                RO  2007   
65                        5X2 cinq fois deux                FR  2004   
67    666 - Traue keinem mit dem du schläfst                DE  2002   
...                                      ...               ...   ...   
4515                                 [Rec] 2                ES  2009   
4540                       Účastníci zájezdu                CZ  2006   
4541                        Śluby panieńskie                PL  2010   
4542                              Świadectwo                PL  2008   
4543                         Ženy v pokušení                CZ  2010   

      tickets_sold_since_1996  tickets_sold  \
40                     701787        693358   
46                    4252690       4066710   
58                    1090696        736957   
65                    1150178        814942   
67                     677829        677829   
...                       ...           ...   
4515                  1387671       1013091   
4540                   871439        830242   
4541                  1001866       1000373   
4542                  1039901       1034911   
4543                  1309118       1303914   

                                 title_merge tconst primary_title  \
40                                        23    NaN           NaN   
46                             28 days later    NaN           NaN   
58             4 luni, 3 saptamani si 2 zile    NaN           NaN   
65                        5x2 cinq fois deux    NaN           NaN   
67    666 - traue keinem mit dem du schläfst    NaN           NaN   
...                                      ...    ...           ...   
4515                                 [rec] 2    NaN           NaN   
4540                       účastníci zájezdu    NaN           NaN   
4541                        śluby panieńskie    NaN           NaN   
4542                              świadectwo    NaN           NaN   
4543                         ženy v pokušení    NaN           NaN   

     original_title runtime  ...  directors_count  director_name  \
40              NaN     NaN  ...              NaN            NaN   
46              NaN     NaN  ...              NaN            NaN   
58              NaN     NaN  ...              NaN            NaN   
65              NaN     NaN  ...              NaN            NaN   
67              NaN     NaN  ...              NaN            NaN   
...             ...     ...  ...              ...            ...   
4515            NaN     NaN  ...              NaN            NaN   
4540            NaN     NaN  ...              NaN            NaN   
4541            NaN     NaN  ...              NaN            NaN   
4542            NaN     NaN  ...              NaN            NaN   
4543            NaN     NaN  ...              NaN            NaN   

      director2_name director3_name writers_count writer_name writer2_name  \
40               NaN            NaN           NaN         NaN          NaN   
46               NaN            NaN           NaN         NaN          NaN   
58               NaN            NaN           NaN         NaN          NaN   
65               NaN            NaN           NaN         NaN          NaN   
67               NaN            NaN           NaN         NaN          NaN   
...              ...            ...           ...         ...          ...   
4515             NaN            NaN           NaN         NaN          NaN   
4540             NaN            NaN           NaN         NaN          NaN   
4541             NaN            NaN           NaN         NaN          NaN   
4542             NaN            NaN           NaN         NaN          NaN   
4543             NaN            NaN           NaN         NaN          NaN   

     writer3_name is_adult

In [29]:
imdb_df[imdb_df["original_title"] == "Paparazzi"]

tconst   primary_title original_title  year runtime  num_votes  \
2350    tt0133314  Paparazzi (FR)      Paparazzi  1998     111     1091.0   
4551    tt0174105  Paparazzi (IT)      Paparazzi  1998     100     1156.0   
16504   tt0338325       Paparazzi      Paparazzi  2004      84    15776.0   
153851  tt5303564       Paparazzi      Paparazzi  2015     110       54.0   

        average_rating  genres_count   genre   genre2  ... directors_count  \
2350               5.4           2.0  Comedy  Romance  ...             1.0   
4551               4.0           1.0  Comedy     None  ...             1.0   
16504              5.7           3.0  Action    Crime  ...             1.0   
153851             5.4           3.0  Action    Drama  ...             1.0   

          director_name director2_name director3_name writers_count  \
2350    Alain Berbérian           None           None           6.0   
4551       Neri Parenti           None           None           NaN   
16504      Paul Abascal           None           None           1.0   
153851     Saad Hendawy           None           None           1.0   

               writer_name         writer2_name writer3_name is_adult  \
2350       Alain Berbérian  Jean-François Halin         None        0   
4551                  None                 None         None        0   
16504          Forry Smith                 None         None        0   
153851  Ahmed Abdel Fattah                 None         None        0   

       original_title_merge  
2350              paparazzi  
4551              paparazzi  
16504             paparazzi  
153851            paparazzi  

[4 rows x 26 columns]

ok, we changed the primary but not the original title ... <br><br>

### Make Beast and Paparazzi correct name in original_title, too.

Paparazzi

In [30]:
imdb_df.loc[imdb_df["original_title"] == "Paparazzi", "primary_title"]

2350      Paparazzi (FR)
4551      Paparazzi (IT)
16504          Paparazzi
153851         Paparazzi
Name: primary_title, dtype: object

In [31]:
imdb_df.loc[imdb_df["original_title"] == "Paparazzi", "original_title"] = imdb_df.loc[imdb_df["original_title"] == "Paparazzi", "primary_title"]

In [32]:
imdb_df[imdb_df["original_title"].str.contains("Paparazzi")]

tconst                primary_title               original_title  \
2350    tt0133314               Paparazzi (FR)               Paparazzi (FR)   
4551    tt0174105               Paparazzi (IT)               Paparazzi (IT)   
16504   tt0338325                    Paparazzi                    Paparazzi   
84736   tt1671678  Paparazzi: Full Throttle LA  Paparazzi: Full Throttle LA   
91523   tt1836097    Paparazzi Eye in the Dark    Paparazzi Eye in the Dark   
153851  tt5303564                    Paparazzi                    Paparazzi   

        year runtime  num_votes  average_rating  genres_count        genre  \
2350    1998     111     1091.0             5.4           2.0       Comedy   
4551    1998     100     1156.0             4.0           1.0       Comedy   
16504   2004      84    15776.0             5.7           3.0       Action   
84736   2010      62       15.0             6.5           1.0  Documentary   
91523   2011     142        9.0             6.8           1.0      Mystery   
153851  2015     110       54.0             5.4           3.0       Action   

         genre2  ... directors_count    director_name director2_name  \
2350    Romance  ...             1.0  Alain Berbérian           None   
4551       None  ...             1.0     Neri Parenti           None   
16504     Crime  ...             1.0     Paul Abascal           None   
84736      None  ...             1.0     Daniel Ramos           None   
91523      None  ...             1.0    Bayo Akinfemi           None   
153851    Drama  ...             1.0     Saad Hendawy           None   

       director3_name writers_count         writer_name         writer2_name  \
2350             None           6.0     Alain Berbérian  Jean-François Halin   
4551             None           NaN                None                 None   
16504            None           1.0         Forry Smith                 None   
84736            None           1.0        Daniel Ramos                 None   
91523            None           1.0      Kojo Edu Ansah                 None   
153851           None           1.0  Ahmed Abdel Fattah                 None   

       writer3_name is_adult         original_title_merge  
2350           None        0                    paparazzi  
4551           None        0                    paparazzi  
16504          None        0                    paparazzi  
84736          None        0  paparazzi: full throttle la  
91523          None        0    paparazzi eye in the dark  
153851         None        0                    paparazzi  

[6 rows x 26 columns]

Beast

In [33]:
imdb_df[imdb_df["original_title"] == "Beast"]

tconst primary_title original_title  year runtime  num_votes  \
47684   tt11301946    Beast (IN)          Beast  2022     155    36815.0   
61223   tt13223398    Beast (US)          Beast  2022      93    43487.0   
69002    tt1423333         Beast          Beast  2007      85       14.0   
79841    tt1572501         Beast          Beast  2011      83      609.0   
143254   tt4251006         Beast          Beast  2015      94       71.0   
144339   tt4359322         Beast          Beast  2009      87       10.0   
156764   tt5628302         Beast          Beast  2017     107    16190.0   
165200   tt6463468         Beast          Beast  2018      60       30.0   

        average_rating  genres_count      genre     genre2  ...  \
47684              5.2           3.0     Action     Comedy  ...   
61223              5.6           3.0     Action  Adventure  ...   
69002              7.0           1.0     Horror       None  ...   
79841              5.6           2.0      Drama   Thriller  ...   
143254             6.6           3.0      Crime      Drama  ...   
144339             5.5           1.0     Horror       None  ...   
156764             6.8           3.0      Crime      Drama  ...   
165200             5.8           2.0  Adventure      Drama  ...   

       directors_count      director_name director2_name director3_name  \
47684              1.0  Nelson Dilipkumar           None           None   
61223              1.0  Baltasar Kormákur           None           None   
69002              1.0       Jack Bennett           None           None   
79841              1.0    Christoffer Boe           None           None   
143254             2.0        Sam McKeith    Tom McKeith           None   
144339             1.0         Chris Jupp           None           None   
156764             1.0     Michael Pearce           None           None   
165200             1.0         Ben Strang           None           None   

       writers_count            writer_name       writer2_name writer3_name  \
47684            1.0      Nelson Dilipkumar               None         None   
61223            2.0  Jaime Primak Sullivan         Ryan Engle         None   
69002            1.0           Jack Bennett               None         None   
79841            1.0        Christoffer Boe               None         None   
143254           3.0           Will Howarth        Sam McKeith  Tom McKeith   
144339           2.0             Chris Jupp  Michael J. Murphy         None   
156764           1.0         Michael Pearce               None         None   
165200           1.0             Ben Strang               None         None   

       is_adult original_title_merge  
47684         0                beast  
61223         0                beast  
69002         0                beast  
79841         0                beast  
143254        0                beast  
144339        0                beast  
156764        0                beast  
165200        0                beast  

[8 rows x 26 columns]

In [34]:
imdb_df.loc[imdb_df["original_title"] == "Beast", "original_title"] = imdb_df.loc[imdb_df["original_title"] == "Beast", "primary_title"]

In [35]:
imdb_df[(imdb_df["original_title"].str.startswith("Beast")) & (imdb_df["year"] == 2022)]

tconst  primary_title original_title  year runtime  num_votes  \
47684   tt11301946     Beast (IN)     Beast (IN)  2022     155    36815.0   
61223   tt13223398     Beast (US)     Beast (US)  2022      93    43487.0   
102369  tt21352688  Beast Mode On  Beast Mode On  2022      85       52.0   

        average_rating  genres_count      genre       genre2  ...  \
47684              5.2           3.0     Action       Comedy  ...   
61223              5.6           3.0     Action    Adventure  ...   
102369             6.4           3.0  Biography  Documentary  ...   

       directors_count            director_name director2_name director3_name  \
47684              1.0        Nelson Dilipkumar           None           None   
61223              1.0        Baltasar Kormákur           None           None   
102369             2.0  Julian Alexander Oliver    Najia Khaan           None   

       writers_count            writer_name    writer2_name writer3_name  \
47684            1.0      Nelson Dilipkumar            None         None   
61223            2.0  Jaime Primak Sullivan      Ryan Engle         None   
102369           4.0      Adebayo Akinfenwa  Dele Akinfenwa         None   

       is_adult original_title_merge  
47684         0                beast  
61223         0                beast  
102369        0        beast mode on  

[3 rows x 26 columns]

Recreate the merging column

In [36]:
imdb_df["original_title_merge"] = imdb_df["original_title"].str.lower()

### Merge again and recheck with Beast and Paparazzi Done

In [37]:
eu_check_df = pd.merge(eu_df,imdb_df, how="left", left_on=["title_merge", "year"], right_on=["original_title_merge", "year"])

In [38]:
eu_check_mask = eu_check_df["tconst"].isnull()
eu_check_df[eu_check_mask]

title producing_country  year  \
40                                        23                DE  1998   
46                             28 Days Later                GB  2002   
58             4 luni, 3 saptamani si 2 zile                RO  2007   
65                        5X2 cinq fois deux                FR  2004   
67    666 - Traue keinem mit dem du schläfst                DE  2002   
...                                      ...               ...   ...   
4515                                 [Rec] 2                ES  2009   
4540                       Účastníci zájezdu                CZ  2006   
4541                        Śluby panieńskie                PL  2010   
4542                              Świadectwo                PL  2008   
4543                         Ženy v pokušení                CZ  2010   

      tickets_sold_since_1996  tickets_sold  \
40                     701787        693358   
46                    4252690       4066710   
58                    1090696        736957   
65                    1150178        814942   
67                     677829        677829   
...                       ...           ...   
4515                  1387671       1013091   
4540                   871439        830242   
4541                  1001866       1000373   
4542                  1039901       1034911   
4543                  1309118       1303914   

                                 title_merge tconst primary_title  \
40                                        23    NaN           NaN   
46                             28 days later    NaN           NaN   
58             4 luni, 3 saptamani si 2 zile    NaN           NaN   
65                        5x2 cinq fois deux    NaN           NaN   
67    666 - traue keinem mit dem du schläfst    NaN           NaN   
...                                      ...    ...           ...   
4515                                 [rec] 2    NaN           NaN   
4540                       účastníci zájezdu    NaN           NaN   
4541                        śluby panieńskie    NaN           NaN   
4542                              świadectwo    NaN           NaN   
4543                         ženy v pokušení    NaN           NaN   

     original_title runtime  ...  directors_count  director_name  \
40              NaN     NaN  ...              NaN            NaN   
46              NaN     NaN  ...              NaN            NaN   
58              NaN     NaN  ...              NaN            NaN   
65              NaN     NaN  ...              NaN            NaN   
67              NaN     NaN  ...              NaN            NaN   
...             ...     ...  ...              ...            ...   
4515            NaN     NaN  ...              NaN            NaN   
4540            NaN     NaN  ...              NaN            NaN   
4541            NaN     NaN  ...              NaN            NaN   
4542            NaN     NaN  ...              NaN            NaN   
4543            NaN     NaN  ...              NaN            NaN   

      director2_name director3_name writers_count writer_name writer2_name  \
40               NaN            NaN           NaN         NaN          NaN   
46               NaN            NaN           NaN         NaN          NaN   
58               NaN            NaN           NaN         NaN          NaN   
65               NaN            NaN           NaN         NaN          NaN   
67               NaN            NaN           NaN         NaN          NaN   
...              ...            ...           ...         ...          ...   
4515             NaN            NaN           NaN         NaN          NaN   
4540             NaN            NaN           NaN         NaN          NaN   
4541             NaN            NaN           NaN         NaN          NaN   
4542             NaN            NaN           NaN         NaN          NaN   
4543             NaN            NaN           NaN         NaN          NaN   

     writer3_name is_adult

In [39]:
imdb_df[(imdb_df["original_title"] == "Paparazzi") & eu_check_mask]

Empty DataFrame
Columns: [tconst, primary_title, original_title, year, runtime, num_votes, average_rating, genres_count, genre, genre2, genre3, acting, acting2, acting3, acting4, acting5, directors_count, director_name, director2_name, director3_name, writers_count, writer_name, writer2_name, writer3_name, is_adult, original_title_merge]
Index: []

[0 rows x 26 columns]

Down from 372 to 369 (-3 for Paparazzi and Beast)

What the heck is wrong with the turkish titles though?

In [40]:
imdb_df.loc[imdb_df["tconst"] == "tt0795488", "original_title_merge"]

32084    úcastníci zájezdu
Name: original_title_merge, dtype: object

In [41]:
eu_check_df.loc[eu_check_df["title"] == "Účastníci zájezdu", "title_merge"]

4540    účastníci zájezdu
Name: title_merge, dtype: object

In [42]:
imdb_df.loc[imdb_df["tconst"] == "tt1720223", "original_title_merge"]

86744    sluby panienskie
Name: original_title_merge, dtype: object

In [43]:
eu_check_df.loc[eu_check_df["title"] == "Śluby panieńskie", "title_merge"]

4541    śluby panieńskie
Name: title_merge, dtype: object

In [44]:
imdb_df.loc[imdb_df["tconst"] == "tt1627942", "original_title_merge"]

82746    zeny v pokusení
Name: original_title_merge, dtype: object

In [45]:
eu_check_df.loc[eu_check_df["title"] == "Ženy v pokušení", "title_merge"]

4543    ženy v pokušení
Name: title_merge, dtype: object

č, ś, ń, ž are all normal character in the IMDB data

### Change all polish/special charcters in IMDB, EU and NA to standard

polish characters: ą, ć, ę, ł, ń, ó, ś, ź, ż

In [46]:
from unidecode import unidecode

In [47]:
# test new function:
test = eu_check_df.loc[eu_check_df["title"] == "Ženy v pokušení", "title_merge"].values[0]
display(test)
unidecode(test)

'ženy v pokušení'

'zeny v pokuseni'

In [109]:
imdb_df["original_title_merge"] = imdb_df["original_title_merge"].apply(unidecode)
eu_df["title_merge"] = eu_df["title_merge"].apply(unidecode)
na_df["title_merge"] = na_df["title_merge"].apply(unidecode)

check for improvements

In [49]:
eu_check_df = pd.merge(eu_df,imdb_df, how="left", left_on=["title_merge", "year"], right_on=["original_title_merge", "year"])

In [50]:
eu_check_mask = eu_check_df["tconst"].isnull()
eu_check_df[eu_check_mask]

title producing_country  year  \
40                                        23                DE  1998   
46                             28 Days Later                GB  2002   
65                        5X2 cinq fois deux                FR  2004   
67    666 - Traue keinem mit dem du schläfst                DE  2002   
118                        A Stork's Journey    DE, BE, LU, NO  2017   
...                                      ...               ...   ...   
4471                               Ya Sonra?                TR  2011   
4498                             Zeny v behu                CZ  2019   
4514                          [REC]³ Génesis                ES  2011   
4515                                 [Rec] 2                ES  2009   
4542                              Świadectwo                PL  2008   

      tickets_sold_since_1996  tickets_sold  \
40                     701787        693358   
46                    4252690       4066710   
65                    1150178        814942   
67                     677829        677829   
118                   1862112       1848892   
...                       ...           ...   
4471                   904069        904069   
4498                  1705959       1675569   
4514                   828887        774431   
4515                  1387671       1013091   
4542                  1039901       1034911   

                                 title_merge tconst primary_title  \
40                                        23    NaN           NaN   
46                             28 days later    NaN           NaN   
65                        5x2 cinq fois deux    NaN           NaN   
67    666 - traue keinem mit dem du schlafst    NaN           NaN   
118                        a stork's journey    NaN           NaN   
...                                      ...    ...           ...   
4471                               ya sonra?    NaN           NaN   
4498                             zeny v behu    NaN           NaN   
4514                          [rec]3 genesis    NaN           NaN   
4515                                 [rec] 2    NaN           NaN   
4542                              swiadectwo    NaN           NaN   

     original_title runtime  ...  directors_count  director_name  \
40              NaN     NaN  ...              NaN            NaN   
46              NaN     NaN  ...              NaN            NaN   
65              NaN     NaN  ...              NaN            NaN   
67              NaN     NaN  ...              NaN            NaN   
118             NaN     NaN  ...              NaN            NaN   
...             ...     ...  ...              ...            ...   
4471            NaN     NaN  ...              NaN            NaN   
4498            NaN     NaN  ...              NaN            NaN   
4514            NaN     NaN  ...              NaN            NaN   
4515            NaN     NaN  ...              NaN            NaN   
4542            NaN     NaN  ...              NaN            NaN   

      director2_name director3_name writers_count writer_name writer2_name  \
40               NaN            NaN           NaN         NaN          NaN   
46               NaN            NaN           NaN         NaN          NaN   
65               NaN            NaN           NaN         NaN          NaN   
67               NaN            NaN           NaN         NaN          NaN   
118              NaN            NaN           NaN         NaN          NaN   
...              ...            ...           ...         ...          ...   
4471             NaN            NaN           NaN         NaN          NaN   
4498             NaN            NaN           NaN         NaN          NaN   
4514             NaN            NaN           NaN         NaN          NaN   
4515             NaN            NaN           NaN         NaN          NaN   
4542             NaN            NaN           NaN         NaN          NaN   

     writer3_name is_adult

We went to 345 from 369 ... 
That is an improvement of 24. 

### Let's check the next one on the list: "23"

In [51]:
imdb_df[imdb_df["tconst"] == "tt0126765"]

tconst primary_title                     original_title  year  \
1970  tt0126765            23  23 - Nichts ist so wie es scheint  1998   

     runtime  num_votes  average_rating  genres_count  genre    genre2  ...  \
1970      99     7404.0             7.2           2.0  Drama  Thriller  ...   

     directors_count          director_name director2_name director3_name  \
1970             1.0  Hans-Christian Schmid           None           None   

     writers_count            writer_name     writer2_name      writer3_name  \
1970           3.0  Hans-Christian Schmid  Michael Gutmann  Michael Dierking   

     is_adult               original_title_merge  
1970        0  23 - nichts ist so wie es scheint  

[1 rows x 26 columns]

"23" in the EU data Is called "23 - Nichts ist so wie es scheint" inn the IMDB dataset. 
Let's chickly check NA for that title

In [52]:
na_df[na_df["title_merge"].str.contains("23")]

title release_date    distributor  gross_sales  \
35           2023 Oscar Shorts   2023-02-17       ShortsHD      3023866   
3824             The Number 23   2007-02-23       New Line     35193167   
4017  The Taking of Pelham 123   2009-06-12  Sony Pictures     65452312   

      tickets_sold  release_year               title_merge  
35          280507          2023         2023 oscar shorts  
3824       5115285          2007             the number 23  
4017       8726974          2009  the taking of pelham 123

No 23 in NA Data. Let's adjust the name for EU.

In [53]:
eu_df.loc[eu_df["title_merge"] == "23", "title"] = "23 - Nichts ist so wie es scheint"

### Let's also check 28 Days Later

In [54]:
imdb_df[imdb_df["tconst"] == "tt0289043"]

tconst  primary_title    original_title  year runtime  num_votes  \
12347  tt0289043  28 Days Later  28 Days Later...  2002     113   453540.0   

       average_rating  genres_count  genre  genre2  ... directors_count  \
12347             7.5           3.0  Drama  Horror  ...             1.0   

      director_name director2_name director3_name writers_count   writer_name  \
12347   Danny Boyle           None           None           1.0  Alex Garland   

       writer2_name writer3_name is_adult original_title_merge  
12347          None         None        0     28 days later...  

[1 rows x 26 columns]

hmmm ... the primary title would work ... the original does not ...  

Could I maybe try to do another merge on primary title with the non fitting data only? 

### Create mergable primary title, too with lower and unidecode

In [55]:
imdb_df["primary_title_merge"] = imdb_df["primary_title"].str.lower().apply(unidecode)

In [56]:
second_merge_eu = eu_check_df[eu_check_mask].copy()
second_merge_eu

title producing_country  year  \
40                                        23                DE  1998   
46                             28 Days Later                GB  2002   
65                        5X2 cinq fois deux                FR  2004   
67    666 - Traue keinem mit dem du schläfst                DE  2002   
118                        A Stork's Journey    DE, BE, LU, NO  2017   
...                                      ...               ...   ...   
4471                               Ya Sonra?                TR  2011   
4498                             Zeny v behu                CZ  2019   
4514                          [REC]³ Génesis                ES  2011   
4515                                 [Rec] 2                ES  2009   
4542                              Świadectwo                PL  2008   

      tickets_sold_since_1996  tickets_sold  \
40                     701787        693358   
46                    4252690       4066710   
65                    1150178        814942   
67                     677829        677829   
118                   1862112       1848892   
...                       ...           ...   
4471                   904069        904069   
4498                  1705959       1675569   
4514                   828887        774431   
4515                  1387671       1013091   
4542                  1039901       1034911   

                                 title_merge tconst primary_title  \
40                                        23    NaN           NaN   
46                             28 days later    NaN           NaN   
65                        5x2 cinq fois deux    NaN           NaN   
67    666 - traue keinem mit dem du schlafst    NaN           NaN   
118                        a stork's journey    NaN           NaN   
...                                      ...    ...           ...   
4471                               ya sonra?    NaN           NaN   
4498                             zeny v behu    NaN           NaN   
4514                          [rec]3 genesis    NaN           NaN   
4515                                 [rec] 2    NaN           NaN   
4542                              swiadectwo    NaN           NaN   

     original_title runtime  ...  directors_count  director_name  \
40              NaN     NaN  ...              NaN            NaN   
46              NaN     NaN  ...              NaN            NaN   
65              NaN     NaN  ...              NaN            NaN   
67              NaN     NaN  ...              NaN            NaN   
118             NaN     NaN  ...              NaN            NaN   
...             ...     ...  ...              ...            ...   
4471            NaN     NaN  ...              NaN            NaN   
4498            NaN     NaN  ...              NaN            NaN   
4514            NaN     NaN  ...              NaN            NaN   
4515            NaN     NaN  ...              NaN            NaN   
4542            NaN     NaN  ...              NaN            NaN   

      director2_name director3_name writers_count writer_name writer2_name  \
40               NaN            NaN           NaN         NaN          NaN   
46               NaN            NaN           NaN         NaN          NaN   
65               NaN            NaN           NaN         NaN          NaN   
67               NaN            NaN           NaN         NaN          NaN   
118              NaN            NaN           NaN         NaN          NaN   
...              ...            ...           ...         ...          ...   
4471             NaN            NaN           NaN         NaN          NaN   
4498             NaN            NaN           NaN         NaN          NaN   
4514             NaN            NaN           NaN         NaN          NaN   
4515             NaN            NaN           NaN         NaN          NaN   
4542             NaN            NaN           NaN         NaN          NaN   

     writer3_name is_adult

Drop Columns from merged frame and merge again with new primary title

In [57]:
second_merge_eu.drop(columns = second_merge_eu.iloc[:,6:], inplace=True)

In [58]:
second_merge_eu = second_merge_eu.merge(imdb_df, how="inner", left_on=["title_merge", "year"], right_on=["primary_title_merge", "year"])

In [59]:
second_merge_eu.shape

(46, 32)

In [60]:
eu_check_df.shape

(4544, 31)

In [61]:
second_merge_mask = eu_check_df["title"].isin(list(second_merge_eu["title"]))
second_merge_mask.sum()

eu_check_df.drop(eu_check_df[second_merge_mask].index, inplace=True)

In [62]:
eu_check_df = pd.concat([eu_check_df, second_merge_eu])
eu_check_df.reset_index(drop=True, inplace=True)
eu_check_df

title producing_country  \
0                                  (500) Days of Summer                US   
1                                          (Nie)znajomi                PL   
2                    (T)Raumschiff Surprise - Periode 1                DE   
3     1 1/2 Ritter - Auf der Suche nach der hinreiße...                DE   
4                                        1 chance sur 2                FR   
...                                                 ...               ...   
4539                                        Tom & Jerry                US   
4540                                       Two Brothers            FR, GB   
4541                                         Van Wilder            US, DE   
4542                                         Wolf Totem            CN, FR   
4543                                 X-Men: First Class            US, GB   

      year  tickets_sold_since_1996  tickets_sold  \
0     2009                  1713086       1684771   
1     2019                   685075        684833   
2     2004                 10763531      10731881   
3     2008                  1986168       1986168   
4     1998                  1295620       1238175   
...    ...                      ...           ...   
4539  2021                  2988828       2982401   
4540  2004                  5029977       4897605   
4541  2002                  2328440       2312108   
4542  2015                  2118880       2087865   
4543  2011                  8254269       8238347   

                                            title_merge      tconst  \
0                                  (500) days of summer   tt1022603   
1                                          (nie)znajomi  tt10518924   
2                    (t)raumschiff surprise - periode 1   tt0349047   
3     1 1/2 ritter - auf der suche nach der hinreiss...   tt1187047   
4                                        1 chance sur 2   tt0119247   
...                                                 ...         ...   
4539                                        tom & jerry   tt1361336   
4540                                       two brothers   tt0338512   
4541                                         van wilder   tt0283111   
4542                                         wolf totem   tt2909116   
4543                                 x-men: first class   tt1270798   

                                          primary_title  \
0                                    500 Days of Summer   
1                                          (Nie)znajomi   
2                    (T)Raumschiff Surprise - Periode 1   
3     1½ Knights - In Search of the Ravishing Prince...   
4                                         Half a Chance   
...                                                 ...   
4539                                        Tom & Jerry   
4540                                       Two Brothers   
4541                                         Van Wilder   
4542                                         Wolf Totem   
4543                                 X-Men: First Class   

                                         original_title runtime  ...  \
0                                  (500) Days of Summer      95  ...   
1                                          (Nie)znajomi     103  ...   
2                    (T)Raumschiff Surprise - Periode 1      87  ...   
3     1 1/2 Ritter - Auf der Suche nach der hinreiße...     115  ...   
4                                        1 chance sur 2     104  ...   
...                                                 ...     ...  ...   
4539                                      Tom and Jerry     101  ...   
4540                                        Deux frères     109  ...   
4541                      National Lampoon's Van Wilder      92  ...   
4542                                    Le dernier loup     121  ...   
4543                                     X: First Class     131  ...   

            director_name    director2_name  director3_name w

In [63]:
eu_check_mask = eu_check_df["tconst"].isnull()
eu_check_df[eu_check_mask]

title producing_country  year  \
63                        5X2 cinq fois deux                FR  2004   
65    666 - Traue keinem mit dem du schläfst                DE  2002   
116                        A Stork's Journey    DE, BE, LU, NO  2017   
122           A todo tren 2: Ahora son ellas                ES  2022   
140                               Adaptation                US  2002   
...                                      ...               ...   ...   
4425                               Ya Sonra?                TR  2011   
4452                             Zeny v behu                CZ  2019   
4468                          [REC]³ Génesis                ES  2011   
4469                                 [Rec] 2                ES  2009   
4496                              Świadectwo                PL  2008   

      tickets_sold_since_1996  tickets_sold  \
63                    1150178        814942   
65                     677829        677829   
116                   1862112       1848892   
122                    946416        669302   
140                   1224151       1217905   
...                       ...           ...   
4425                   904069        904069   
4452                  1705959       1675569   
4468                   828887        774431   
4469                  1387671       1013091   
4496                  1039901       1034911   

                                 title_merge tconst primary_title  \
63                        5x2 cinq fois deux    NaN           NaN   
65    666 - traue keinem mit dem du schlafst    NaN           NaN   
116                        a stork's journey    NaN           NaN   
122           a todo tren 2: ahora son ellas    NaN           NaN   
140                               adaptation    NaN           NaN   
...                                      ...    ...           ...   
4425                               ya sonra?    NaN           NaN   
4452                             zeny v behu    NaN           NaN   
4468                          [rec]3 genesis    NaN           NaN   
4469                                 [rec] 2    NaN           NaN   
4496                              swiadectwo    NaN           NaN   

     original_title runtime  ...  director_name  director2_name  \
63              NaN     NaN  ...            NaN             NaN   
65              NaN     NaN  ...            NaN             NaN   
116             NaN     NaN  ...            NaN             NaN   
122             NaN     NaN  ...            NaN             NaN   
140             NaN     NaN  ...            NaN             NaN   
...             ...     ...  ...            ...             ...   
4425            NaN     NaN  ...            NaN             NaN   
4452            NaN     NaN  ...            NaN             NaN   
4468            NaN     NaN  ...            NaN             NaN   
4469            NaN     NaN  ...            NaN             NaN   
4496            NaN     NaN  ...            NaN             NaN   

      director3_name writers_count writer_name writer2_name writer3_name  \
63               NaN           NaN         NaN          NaN          NaN   
65               NaN           NaN         NaN          NaN          NaN   
116              NaN           NaN         NaN          NaN          NaN   
122              NaN           NaN         NaN          NaN          NaN   
140              NaN           NaN         NaN          NaN          NaN   
...              ...           ...         ...          ...          ...   
4425             NaN           NaN         NaN          NaN          NaN   
4452             NaN           NaN         NaN          NaN          NaN   
4468             NaN           NaN         NaN          NaN          NaN   
4469             NaN           NaN         NaN          NaN          NaN   
4496             NaN           NaN         NaN          NaN          NaN   

     is_adult original_title_merge primary_title_merge  
63   

After mergeing again on primary title, number of unmachted reduced from 345 to 299.
That is an improvement by 46. 

But merging now is more complicated. 

### Let's write a merging function for original than primary to use in the following tests.

In [64]:
def double_merge_func(ticket_data, base_data = imdb_df):
    '''
    Merges our Tickets Sold Dataframes First on the newly created original title than second on the primary title and keeps only hits from both.

    Input:
        ticket_data ... either eu or na depending on what we are testing
        base_data = imdb_df

    Output:
        Returns: Dataframe with all matches from both columns
        Prints: Unmatched rows
    '''
    # first merge
    check_df = pd.merge(ticket_data,base_data, how="left", left_on=["title_merge", "year"], right_on=["original_title_merge", "year"])

    # set-up second df for further calculations
    check_mask = check_df["tconst"].isnull()
    second_merge_df = check_df[check_mask].copy()
    second_merge_df

    # drop columns from first merge
    second_merge_df.drop(columns = second_merge_df.iloc[:,6:], inplace=True)

    # second merge (inner)
    second_merge_df = second_merge_df.merge(base_data, how="inner", left_on=["title_merge", "year"], right_on=["primary_title_merge", "year"])

    # drop columns from first merge table that matched on second merge
    second_merge_mask = check_df["title"].isin(list(second_merge_df["title"]))
    check_df.drop(check_df[second_merge_mask].index, inplace=True)

    # add fitting rows from second merge to first table
    check_df = pd.concat([check_df, second_merge_df])
    check_df.reset_index(drop=True, inplace=True)

    # show unmatched rows
    check_mask = check_df["tconst"].isnull()
    display(check_df[check_mask])
    
    return check_df

In [65]:
double_merge_func(eu_df)

title producing_country  year  \
63                        5X2 cinq fois deux                FR  2004   
65    666 - Traue keinem mit dem du schläfst                DE  2002   
116                        A Stork's Journey    DE, BE, LU, NO  2017   
122           A todo tren 2: Ahora son ellas                ES  2022   
140                               Adaptation                US  2002   
...                                      ...               ...   ...   
4425                               Ya Sonra?                TR  2011   
4452                             Zeny v behu                CZ  2019   
4468                          [REC]³ Génesis                ES  2011   
4469                                 [Rec] 2                ES  2009   
4496                              Świadectwo                PL  2008   

      tickets_sold_since_1996  tickets_sold  \
63                    1150178        814942   
65                     677829        677829   
116                   1862112       1848892   
122                    946416        669302   
140                   1224151       1217905   
...                       ...           ...   
4425                   904069        904069   
4452                  1705959       1675569   
4468                   828887        774431   
4469                  1387671       1013091   
4496                  1039901       1034911   

                                 title_merge tconst primary_title  \
63                        5x2 cinq fois deux    NaN           NaN   
65    666 - traue keinem mit dem du schlafst    NaN           NaN   
116                        a stork's journey    NaN           NaN   
122           a todo tren 2: ahora son ellas    NaN           NaN   
140                               adaptation    NaN           NaN   
...                                      ...    ...           ...   
4425                               ya sonra?    NaN           NaN   
4452                             zeny v behu    NaN           NaN   
4468                          [rec]3 genesis    NaN           NaN   
4469                                 [rec] 2    NaN           NaN   
4496                              swiadectwo    NaN           NaN   

     original_title runtime  ...  director_name  director2_name  \
63              NaN     NaN  ...            NaN             NaN   
65              NaN     NaN  ...            NaN             NaN   
116             NaN     NaN  ...            NaN             NaN   
122             NaN     NaN  ...            NaN             NaN   
140             NaN     NaN  ...            NaN             NaN   
...             ...     ...  ...            ...             ...   
4425            NaN     NaN  ...            NaN             NaN   
4452            NaN     NaN  ...            NaN             NaN   
4468            NaN     NaN  ...            NaN             NaN   
4469            NaN     NaN  ...            NaN             NaN   
4496            NaN     NaN  ...            NaN             NaN   

      director3_name writers_count writer_name writer2_name writer3_name  \
63               NaN           NaN         NaN          NaN          NaN   
65               NaN           NaN         NaN          NaN          NaN   
116              NaN           NaN         NaN          NaN          NaN   
122              NaN           NaN         NaN          NaN          NaN   
140              NaN           NaN         NaN          NaN          NaN   
...              ...           ...         ...          ...          ...   
4425             NaN           NaN         NaN          NaN          NaN   
4452             NaN           NaN         NaN          NaN          NaN   
4468             NaN           NaN         NaN          NaN          NaN   
4469             NaN           NaN         NaN          NaN          NaN   
4496             NaN           NaN         NaN          NaN          NaN   

     is_adult original_title_merge primary_title_merge  
63   

title producing_country  \
0                                  (500) Days of Summer                US   
1                                          (Nie)znajomi                PL   
2                    (T)Raumschiff Surprise - Periode 1                DE   
3     1 1/2 Ritter - Auf der Suche nach der hinreiße...                DE   
4                                        1 chance sur 2                FR   
...                                                 ...               ...   
4539                                        Tom & Jerry                US   
4540                                       Two Brothers            FR, GB   
4541                                         Van Wilder            US, DE   
4542                                         Wolf Totem            CN, FR   
4543                                 X-Men: First Class            US, GB   

      year  tickets_sold_since_1996  tickets_sold  \
0     2009                  1713086       1684771   
1     2019                   685075        684833   
2     2004                 10763531      10731881   
3     2008                  1986168       1986168   
4     1998                  1295620       1238175   
...    ...                      ...           ...   
4539  2021                  2988828       2982401   
4540  2004                  5029977       4897605   
4541  2002                  2328440       2312108   
4542  2015                  2118880       2087865   
4543  2011                  8254269       8238347   

                                            title_merge      tconst  \
0                                  (500) days of summer   tt1022603   
1                                          (nie)znajomi  tt10518924   
2                    (t)raumschiff surprise - periode 1   tt0349047   
3     1 1/2 ritter - auf der suche nach der hinreiss...   tt1187047   
4                                        1 chance sur 2   tt0119247   
...                                                 ...         ...   
4539                                        tom & jerry   tt1361336   
4540                                       two brothers   tt0338512   
4541                                         van wilder   tt0283111   
4542                                         wolf totem   tt2909116   
4543                                 x-men: first class   tt1270798   

                                          primary_title  \
0                                    500 Days of Summer   
1                                          (Nie)znajomi   
2                    (T)Raumschiff Surprise - Periode 1   
3     1½ Knights - In Search of the Ravishing Prince...   
4                                         Half a Chance   
...                                                 ...   
4539                                        Tom & Jerry   
4540                                       Two Brothers   
4541                                         Van Wilder   
4542                                         Wolf Totem   
4543                                 X-Men: First Class   

                                         original_title runtime  ...  \
0                                  (500) Days of Summer      95  ...   
1                                          (Nie)znajomi     103  ...   
2                    (T)Raumschiff Surprise - Periode 1      87  ...   
3     1 1/2 Ritter - Auf der Suche nach der hinreiße...     115  ...   
4                                        1 chance sur 2     104  ...   
...                                                 ...     ...  ...   
4539                                      Tom and Jerry     101  ...   
4540                                        Deux frères     109  ...   
4541                      National Lampoon's Van Wilder      92  ...   
4542                                    Le dernier loup     121  ...   
4543                                     X: First Class     131  ...   

            director_name    director2_name  director3_name w

### Let's keep on checking the remaining problems ...

In [66]:
eu_check_df = double_merge_func(eu_df)

title producing_country  year  \
63                        5X2 cinq fois deux                FR  2004   
65    666 - Traue keinem mit dem du schläfst                DE  2002   
116                        A Stork's Journey    DE, BE, LU, NO  2017   
122           A todo tren 2: Ahora son ellas                ES  2022   
140                               Adaptation                US  2002   
...                                      ...               ...   ...   
4425                               Ya Sonra?                TR  2011   
4452                             Zeny v behu                CZ  2019   
4468                          [REC]³ Génesis                ES  2011   
4469                                 [Rec] 2                ES  2009   
4496                              Świadectwo                PL  2008   

      tickets_sold_since_1996  tickets_sold  \
63                    1150178        814942   
65                     677829        677829   
116                   1862112       1848892   
122                    946416        669302   
140                   1224151       1217905   
...                       ...           ...   
4425                   904069        904069   
4452                  1705959       1675569   
4468                   828887        774431   
4469                  1387671       1013091   
4496                  1039901       1034911   

                                 title_merge tconst primary_title  \
63                        5x2 cinq fois deux    NaN           NaN   
65    666 - traue keinem mit dem du schlafst    NaN           NaN   
116                        a stork's journey    NaN           NaN   
122           a todo tren 2: ahora son ellas    NaN           NaN   
140                               adaptation    NaN           NaN   
...                                      ...    ...           ...   
4425                               ya sonra?    NaN           NaN   
4452                             zeny v behu    NaN           NaN   
4468                          [rec]3 genesis    NaN           NaN   
4469                                 [rec] 2    NaN           NaN   
4496                              swiadectwo    NaN           NaN   

     original_title runtime  ...  director_name  director2_name  \
63              NaN     NaN  ...            NaN             NaN   
65              NaN     NaN  ...            NaN             NaN   
116             NaN     NaN  ...            NaN             NaN   
122             NaN     NaN  ...            NaN             NaN   
140             NaN     NaN  ...            NaN             NaN   
...             ...     ...  ...            ...             ...   
4425            NaN     NaN  ...            NaN             NaN   
4452            NaN     NaN  ...            NaN             NaN   
4468            NaN     NaN  ...            NaN             NaN   
4469            NaN     NaN  ...            NaN             NaN   
4496            NaN     NaN  ...            NaN             NaN   

      director3_name writers_count writer_name writer2_name writer3_name  \
63               NaN           NaN         NaN          NaN          NaN   
65               NaN           NaN         NaN          NaN          NaN   
116              NaN           NaN         NaN          NaN          NaN   
122              NaN           NaN         NaN          NaN          NaN   
140              NaN           NaN         NaN          NaN          NaN   
...              ...           ...         ...          ...          ...   
4425             NaN           NaN         NaN          NaN          NaN   
4452             NaN           NaN         NaN          NaN          NaN   
4468             NaN           NaN         NaN          NaN          NaN   
4469             NaN           NaN         NaN          NaN          NaN   
4496             NaN           NaN         NaN          NaN          NaN   

     is_adult original_title_merge primary_title_merge  
63   

In [67]:
imdb_df[imdb_df["tconst"] == "tt0354356"]

tconst   primary_title original_title  year runtime  num_votes  \
17678  tt0354356  Five Times Two            5x2  2004      90    10498.0   

       average_rating  genres_count  genre   genre2  ...  director_name  \
17678             6.6           2.0  Drama  Romance  ...  François Ozon   

      director2_name director3_name writers_count    writer_name  \
17678           None           None           2.0  François Ozon   

             writer2_name  writer3_name is_adult original_title_merge  \
17678  Emmanuèle Bernheim          None        0                  5x2   

      primary_title_merge  
17678      five times two  

[1 rows x 27 columns]

In [68]:
eu_df.loc[eu_df["title_merge"].str.contains("5x2"), "title_merge"] = "5x2"
eu_df.loc[eu_df["title_merge"].str.contains("5x2"), :]

title producing_country  year  tickets_sold_since_1996  \
65  5X2 cinq fois deux                FR  2004                  1150178   

    tickets_sold title_merge  
65        814942         5x2

In [69]:
imdb_df[imdb_df["tconst"] == "tt0291167"]

tconst               primary_title  \
12552  tt0291167  666: In Bed with the Devil   

                                 original_title  year runtime  num_votes  \
12552  666 - Traue keinem, mit dem Du schläfst!  2002      85      886.0   

       average_rating  genres_count   genre genre2  ...     director_name  \
12552             5.3           1.0  Comedy   None  ...  Rainer Matsutani   

      director2_name director3_name writers_count                 writer_name  \
12552           None           None           2.0  Johann Wolfgang von Goethe   

           writer2_name  writer3_name is_adult  \
12552  Rainer Matsutani          None        0   

                           original_title_merge         primary_title_merge  
12552  666 - traue keinem, mit dem du schlafst!  666: in bed with the devil  

[1 rows x 27 columns]

In [70]:
eu_df.loc[eu_df["title_merge"].str.contains("666"),"title_merge"] = "666 - traue keinem, mit dem du schlafst!"
eu_df.loc[eu_df["title_merge"].str.contains("666"),:]

title producing_country  year  \
67  666 - Traue keinem mit dem du schläfst                DE  2002   

    tickets_sold_since_1996  tickets_sold  \
67                   677829        677829   

                                 title_merge  
67  666 - traue keinem, mit dem du schlafst!

In [71]:
imdb_df[imdb_df["tconst"] == "tt3823116"]

tconst                primary_title  \
138475  tt3823116  Little Bird's Big Adventure   

                                      original_title  year runtime  num_votes  \
138475  Überflieger - Kleine Vögel, großes Geklapper  2017      85     2377.0   

        average_rating  genres_count      genre     genre2  ... director_name  \
138475             5.8           3.0  Adventure  Animation  ...   Toby Genkel   

       director2_name director3_name writers_count  writer_name  \
138475    Reza Memari           None           4.0  Reza Memari   

             writer2_name  writer3_name is_adult  \
138475  Anne D. Bernstein          None        0   

                                 original_title_merge  \
138475  uberflieger - kleine vogel, grosses geklapper   

                primary_title_merge  
138475  little bird's big adventure  

[1 rows x 27 columns]

In [72]:
eu_df.loc[eu_df["title_merge"] == "a stork's journey", "title_merge"] = "uberflieger - kleine vogel, grosses geklapper"
eu_df.loc[eu_df["title_merge"].str.contains("uberflieger"), :]

title producing_country  year  tickets_sold_since_1996  \
118  A Stork's Journey    DE, BE, LU, NO  2017                  1862112   

     tickets_sold                                    title_merge  
118       1848892  uberflieger - kleine vogel, grosses geklapper

In [73]:
imdb_df[imdb_df["tconst"] == "tt21335908"]

tconst           primary_title  \
102258  tt21335908  The Kids Are Alright 2   

                                   original_title  year runtime  num_votes  \
102258  A Todo Tren 2: Sí, les ha pasado otra vez  2022      84     4678.0   

        average_rating  genres_count   genre genre2  ... director_name  \
102258             4.5           1.0  Comedy   None  ...  Inés de León   

       director2_name director3_name writers_count             writer_name  \
102258           None           None           2.0  Marta González de Vega   

           writer2_name  writer3_name is_adult  \
102258  Santiago Segura          None        0   

                             original_title_merge     primary_title_merge  
102258  a todo tren 2: si, les ha pasado otra vez  the kids are alright 2  

[1 rows x 27 columns]

In [74]:
eu_df.loc[eu_df["title_merge"].str.contains("a todo tren 2"), "title_merge"] = "a todo tren 2: si, les ha pasado otra vez"
eu_df.loc[eu_df["title_merge"].str.contains("a todo tren 2"), :]

title producing_country  year  \
124  A todo tren 2: Ahora son ellas                ES  2022   

     tickets_sold_since_1996  tickets_sold  \
124                   946416        669302   

                                   title_merge  
124  a todo tren 2: si, les ha pasado otra vez

corrected 5 manually ... this will be tedious if all 300 remaining unmatching rows have to be done by hand ...

### Let's check again after those 5 are gone -> strip all punctuations from the merging strings

In [75]:
eu_check_df = double_merge_func(eu_df)

title producing_country  year  \
140                  Adaptation                US  2002   
147                African Cats                US  2011   
159                  Agir Roman        TR, FR, HU  1998   
191   Allahin Sadik Kulu: Barla                TR  2011   
212                        Amen        FR, DE, RO  2002   
...                         ...               ...   ...   
4425                  Ya Sonra?                TR  2011   
4452                Zeny v behu                CZ  2019   
4468             [REC]³ Génesis                ES  2011   
4469                    [Rec] 2                ES  2009   
4496                 Świadectwo                PL  2008   

      tickets_sold_since_1996  tickets_sold                title_merge tconst  \
140                   1224151       1217905                 adaptation    NaN   
147                    803485        794169               african cats    NaN   
159                    850000        850000                 agir roman    NaN   
191                   2279419       2226422  allahin sadik kulu: barla    NaN   
212                   1932487       1687019                       amen    NaN   
...                       ...           ...                        ...    ...   
4425                   904069        904069                  ya sonra?    NaN   
4452                  1705959       1675569                zeny v behu    NaN   
4468                   828887        774431             [rec]3 genesis    NaN   
4469                  1387671       1013091                    [rec] 2    NaN   
4496                  1039901       1034911                 swiadectwo    NaN   

     primary_title original_title runtime  ...  director_name  director2_name  \
140            NaN            NaN     NaN  ...            NaN             NaN   
147            NaN            NaN     NaN  ...            NaN             NaN   
159            NaN            NaN     NaN  ...            NaN             NaN   
191            NaN            NaN     NaN  ...            NaN             NaN   
212            NaN            NaN     NaN  ...            NaN             NaN   
...            ...            ...     ...  ...            ...             ...   
4425           NaN            NaN     NaN  ...            NaN             NaN   
4452           NaN            NaN     NaN  ...            NaN             NaN   
4468           NaN            NaN     NaN  ...            NaN             NaN   
4469           NaN            NaN     NaN  ...            NaN             NaN   
4496           NaN            NaN     NaN  ...            NaN             NaN   

      director3_name writers_count writer_name writer2_name writer3_name  \
140              NaN           NaN         NaN          NaN          NaN   
147              NaN           NaN         NaN          NaN          NaN   
159              NaN           NaN         NaN          NaN          NaN   
191              NaN           NaN         NaN          NaN          NaN   
212              NaN           NaN         NaN          NaN          NaN   
...              ...           ...         ...          ...          ...   
4425             NaN           NaN         NaN          NaN          NaN   
4452             NaN           NaN         NaN          NaN          NaN   
4468             NaN           NaN         NaN          NaN          NaN   
4469             NaN           NaN         NaN          NaN          NaN   
4496             NaN           NaN         NaN          NaN          NaN   

     is_adult original_title_merge primary_title_merge  
140       NaN                  NaN                 NaN  
147       NaN                  NaN                 NaN  
159       NaN                  NaN                 NaN  
191       NaN                  NaN                 NaN  
212       NaN                  NaN                 NaN  
...       ...                  ...                 ...  
4425      NaN                  NaN                 NaN  
44

In [76]:
imdb_df[imdb_df["tconst"] == "tt0268126"]

tconst primary_title original_title  year runtime  num_votes  \
10377  tt0268126   Adaptation.    Adaptation.  2002     115   205067.0   

       average_rating  genres_count   genre genre2  ... director_name  \
10377             7.7           2.0  Comedy  Drama  ...   Spike Jonze   

      director2_name director3_name writers_count   writer_name  \
10377           None           None           2.0  Susan Orlean   

          writer2_name  writer3_name is_adult original_title_merge  \
10377  Charlie Kaufman          None        0          adaptation.   

      primary_title_merge  
10377         adaptation.  

[1 rows x 27 columns]

ok this is the third movie which oes not fit because IMDB added .!... or anything like that to the end of it.. .

In [77]:
import string as string

In [78]:
imdb_df["original_title_merge"] = imdb_df["original_title_merge"].str.translate(str.maketrans("","",string.punctuation))
imdb_df["primary_title_merge"] = imdb_df["primary_title_merge"].str.translate(str.maketrans("","",string.punctuation))

eu_df["title_merge"] = eu_df["title_merge"].str.translate(str.maketrans("","",string.punctuation))
na_df["title_merge"] = na_df["title_merge"].str.translate(str.maketrans("","",string.punctuation))

In [79]:
eu_check_df = double_merge_func(eu_df)

title producing_country  year  \
149                               African Cats                US  2011   
161                                 Agir Roman        TR, FR, HU  1998   
225                             American Pie 4                US  2012   
260                                Angry Birds            US, FI  2016   
261    Angus, Thongs and Full-Frontal Snogging     GBinc, US, DE  2008   
...                                        ...               ...   ...   
4396  Winx club - Il segreto del regno perduto                IT  2007   
4459                               Zeny v behu                CZ  2019   
4475                            [REC]³ Génesis                ES  2011   
4476                                   [Rec] 2                ES  2009   
4503                                Świadectwo                PL  2008   

      tickets_sold_since_1996  tickets_sold  \
149                    803485        794169   
161                    850000        850000   
225                  12501353      12500536   
260                  10228756      10217533   
261                   1358397       1346801   
...                       ...           ...   
4396                  2217926       2132336   
4459                  1705959       1675569   
4475                   828887        774431   
4476                  1387671       1013091   
4503                  1039901       1034911   

                                  title_merge tconst primary_title  \
149                              african cats    NaN           NaN   
161                                agir roman    NaN           NaN   
225                            american pie 4    NaN           NaN   
260                               angry birds    NaN           NaN   
261     angus thongs and fullfrontal snogging    NaN           NaN   
...                                       ...    ...           ...   
4396  winx club  il segreto del regno perduto    NaN           NaN   
4459                              zeny v behu    NaN           NaN   
4475                             rec3 genesis    NaN           NaN   
4476                                    rec 2    NaN           NaN   
4503                               swiadectwo    NaN           NaN   

     original_title runtime  ...  director_name  director2_name  \
149             NaN     NaN  ...            NaN             NaN   
161             NaN     NaN  ...            NaN             NaN   
225             NaN     NaN  ...            NaN             NaN   
260             NaN     NaN  ...            NaN             NaN   
261             NaN     NaN  ...            NaN             NaN   
...             ...     ...  ...            ...             ...   
4396            NaN     NaN  ...            NaN             NaN   
4459            NaN     NaN  ...            NaN             NaN   
4475            NaN     NaN  ...            NaN             NaN   
4476            NaN     NaN  ...            NaN             NaN   
4503            NaN     NaN  ...            NaN             NaN   

      director3_name writers_count writer_name writer2_name writer3_name  \
149              NaN           NaN         NaN          NaN          NaN   
161              NaN           NaN         NaN          NaN          NaN   
225              NaN           NaN         NaN          NaN          NaN   
260              NaN           NaN         NaN          NaN          NaN   
261              NaN           NaN         NaN          NaN          NaN   
...              ...           ...         ...          ...          ...   
4396             NaN           NaN         NaN          NaN          NaN   
4459             NaN           NaN         NaN          NaN          NaN   
4475             NaN           NaN         NaN          NaN          NaN   
4476             NaN           NaN         NaN          NaN          NaN   
4503             NaN           NaN         NaN          NaN          NaN   

     is_adult original_title

Stripping punctuations resulted in 255 unmachted rows (from 295). That is an improvement by 40

### Let's check the remaining again for new Ideas

OK IDEA: we merge again with remaining but do year +/- 1

In [80]:
imdb_df[imdb_df["tconst"] == "tt1223236"]

tconst primary_title original_title  year runtime  num_votes  \
54210  tt1223236  African Cats   African Cats  2010      89     6776.0   

       average_rating  genres_count      genre       genre2  ...  \
54210             7.5           2.0  Adventure  Documentary  ...   

       director_name       director2_name director3_name writers_count  \
54210  Keith Scholey  Alastair Fothergill           None           3.0   

         writer_name writer2_name  writer3_name is_adult original_title_merge  \
54210  Keith Scholey   John Truby   Owen Newman        0         african cats   

      primary_title_merge  
54210        african cats  

[1 rows x 27 columns]

hmm maybe I should, only for the unmatching rows, create two new year columns with +1 and -1 and check again. There might be cases in which the movie has different dates in IMDB and the tickets data bases.

In [81]:
eu_unmatched_df = eu_check_df.loc[eu_check_df["tconst"].isnull(),:].copy()
eu_unmatched_df

title producing_country  year  \
149                               African Cats                US  2011   
161                                 Agir Roman        TR, FR, HU  1998   
225                             American Pie 4                US  2012   
260                                Angry Birds            US, FI  2016   
261    Angus, Thongs and Full-Frontal Snogging     GBinc, US, DE  2008   
...                                        ...               ...   ...   
4396  Winx club - Il segreto del regno perduto                IT  2007   
4459                               Zeny v behu                CZ  2019   
4475                            [REC]³ Génesis                ES  2011   
4476                                   [Rec] 2                ES  2009   
4503                                Świadectwo                PL  2008   

      tickets_sold_since_1996  tickets_sold  \
149                    803485        794169   
161                    850000        850000   
225                  12501353      12500536   
260                  10228756      10217533   
261                   1358397       1346801   
...                       ...           ...   
4396                  2217926       2132336   
4459                  1705959       1675569   
4475                   828887        774431   
4476                  1387671       1013091   
4503                  1039901       1034911   

                                  title_merge tconst primary_title  \
149                              african cats    NaN           NaN   
161                                agir roman    NaN           NaN   
225                            american pie 4    NaN           NaN   
260                               angry birds    NaN           NaN   
261     angus thongs and fullfrontal snogging    NaN           NaN   
...                                       ...    ...           ...   
4396  winx club  il segreto del regno perduto    NaN           NaN   
4459                              zeny v behu    NaN           NaN   
4475                             rec3 genesis    NaN           NaN   
4476                                    rec 2    NaN           NaN   
4503                               swiadectwo    NaN           NaN   

     original_title runtime  ...  director_name  director2_name  \
149             NaN     NaN  ...            NaN             NaN   
161             NaN     NaN  ...            NaN             NaN   
225             NaN     NaN  ...            NaN             NaN   
260             NaN     NaN  ...            NaN             NaN   
261             NaN     NaN  ...            NaN             NaN   
...             ...     ...  ...            ...             ...   
4396            NaN     NaN  ...            NaN             NaN   
4459            NaN     NaN  ...            NaN             NaN   
4475            NaN     NaN  ...            NaN             NaN   
4476            NaN     NaN  ...            NaN             NaN   
4503            NaN     NaN  ...            NaN             NaN   

      director3_name writers_count writer_name writer2_name writer3_name  \
149              NaN           NaN         NaN          NaN          NaN   
161              NaN           NaN         NaN          NaN          NaN   
225              NaN           NaN         NaN          NaN          NaN   
260              NaN           NaN         NaN          NaN          NaN   
261              NaN           NaN         NaN          NaN          NaN   
...              ...           ...         ...          ...          ...   
4396             NaN           NaN         NaN          NaN          NaN   
4459             NaN           NaN         NaN          NaN          NaN   
4475             NaN           NaN         NaN          NaN          NaN   
4476             NaN           NaN         NaN          NaN          NaN   
4503             NaN           NaN         NaN          NaN          NaN   

     is_adult original_title

In [82]:
eu_unmatched_df.drop(columns = eu_unmatched_df.iloc[:,6:], inplace=True)
display(eu_unmatched_df.head())
eu_unmatched_df.shape

title producing_country  year  \
149                             African Cats                US  2011   
161                               Agir Roman        TR, FR, HU  1998   
225                           American Pie 4                US  2012   
260                              Angry Birds            US, FI  2016   
261  Angus, Thongs and Full-Frontal Snogging     GBinc, US, DE  2008   

     tickets_sold_since_1996  tickets_sold  \
149                   803485        794169   
161                   850000        850000   
225                 12501353      12500536   
260                 10228756      10217533   
261                  1358397       1346801   

                               title_merge  
149                           african cats  
161                             agir roman  
225                         american pie 4  
260                            angry birds  
261  angus thongs and fullfrontal snogging

(255, 6)

In [83]:
eu_unmatched_df.loc[:,"year_plus"] = eu_unmatched_df["year"] + 1
eu_unmatched_df.loc[:,"year_minus"] = eu_unmatched_df["year"] - 1

In [84]:
eu_unmatched_df.head()

title producing_country  year  \
149                             African Cats                US  2011   
161                               Agir Roman        TR, FR, HU  1998   
225                           American Pie 4                US  2012   
260                              Angry Birds            US, FI  2016   
261  Angus, Thongs and Full-Frontal Snogging     GBinc, US, DE  2008   

     tickets_sold_since_1996  tickets_sold  \
149                   803485        794169   
161                   850000        850000   
225                 12501353      12500536   
260                 10228756      10217533   
261                  1358397       1346801   

                               title_merge  year_plus  year_minus  
149                           african cats       2012        2010  
161                             agir roman       1999        1997  
225                         american pie 4       2013        2011  
260                            angry birds       2017        2015  
261  angus thongs and fullfrontal snogging       2009        2007

In [85]:
eu_unmatched_df.merge(imdb_df, how="inner", left_on=["title_merge", "year_plus"], right_on=["original_title_merge", "year"])

title   producing_country  year_x  \
0                       Arlington Road                  US    1998   
1                 Au coeur du mensonge                  FR    1998   
2                          Baba Parasi                  TR    2019   
3     Belphégor - Le fantôme du Louvre                  FR    2000   
4                   Bon Bini Holland 3                  NL    2021   
..                                 ...                 ...     ...   
58  Une hirondelle a fait le printemps              FR, BE    2000   
59                               Virus  US, GB, JP, DE, FR    1998   
60                           Vizontele                  TR    2000   
61                    Vsetko alebo nic          SK, CZ, PL    2016   
62                      [REC]³ Génesis                  ES    2011   

    tickets_sold_since_1996  tickets_sold                         title_merge  \
0                   2030466       2029739                      arlington road   
1                    933602        828875                au coeur du mensonge   
2                   2071090       1896340                         baba parasi   
3                   3053474       2563623     belphegor  le fantome du louvre   
4                    459342        459296                  bon bini holland 3   
..                      ...           ...                                 ...   
58                  2773596       2340748  une hirondelle a fait le printemps   
59                  1719742       1715116                               virus   
60                  3556294       3556294                           vizontele   
61                   831177        825927                    vsetko alebo nic   
62                   828887        774431                        rec3 genesis   

    year_plus  year_minus      tconst                     primary_title  ...  \
0        1999        1997   tt0137363                    Arlington Road  ...   
1        1999        1997   tt0164368                 The Color of Lies  ...   
2        2020        2018  tt10549312                       Baba Parasi  ...   
3        2001        1999   tt0214529  Belphegor: Phantom of the Louvre  ...   
4        2022        2020  tt11177150                Bon Bini Holland 3  ...   
..        ...         ...         ...                               ...  ...   
58       2001        1999   tt0240149               The Girl from Paris  ...   
59       1999        1997   tt0120458                             Virus  ...   
60       2001        1999   tt0270053                         Vizontele  ...   
61       2017        2015   tt3868240                    All or Nothing  ...   
62       2012        2010   tt1649444                  [REC] 3: Genesis  ...   

       director_name    director2_name director3_name  writers_count  \
0    Mark Pellington              None           None            1.0   
1     Claude Chabrol              None           None            2.0   
2     Selçuk Aydemir              None           None            1.0   
3   Jean-Paul Salomé              None           None            4.0   
4    Pieter van Rijn              None           None            4.0   
..               ...               ...            ...            ...   
58  Christian Carion              None           None            2.0   
59        John Bruno              None           None            2.0   
60    Yilmaz Erdogan  Ömer Faruk Sorak           None            1.0   
61   Marta Ferencova              None           None            2.0   
62        Paco Plaza              None           None            3.0   

         writer_name      writer2_name   writer3_name is_adult  \
0       Ehren Kruger              None           None        0   
1       Odile Barski    Claude Chabrol           None        0   
2     Selçuk Aydemir              None           None        0   
3     Arthur Bernède  Jean-Paul Salomé           None        0   
4      Michel Bonset  Jandino Asporaat           None        0 

In [86]:
eu_unmatched_df.merge(imdb_df, how="inner", left_on=["title_merge", "year_minus"], right_on=["original_title_merge", "year"])

title producing_country  year_x  \
0                                    African Cats                US    2011   
1                                      Agir Roman        TR, FR, HU    1998   
2                          De l'autre côté du lit                FR    2009   
3                 Die Wilden Hühner und die Liebe                DE    2007   
4                               Die wilden Hühner                DE    2006   
5                 Die wilden Hühner und das Leben                DE    2009   
6                                        Drogówka                PL    2013   
7                                 Eddie the Eagle     GBinc, US, DE    2016   
8                                      Ex Machina         GBinc, US    2015   
9                              Fly Me to the Moon            BE, US    2008   
10                                     Gadjo Dilo            FR, RO    1998   
11                           Happily N'Ever After                DE    2007   
12                       Il testimone dello Sposo                IT    1998   
13                                Io, loro e Lara                IT    2010   
14                                 Ja wam pokaze!                PL    2006   
15                                Just the Ticket            US, FR    1999   
16                                   Kahpe Bizans                TR    2000   
17                           L'ex-femme de ma vie         FRinc, US    2005   
18                                    Masterminds                US    2016   
19  Mortadelo y Filemón. Misión: Salvar la Tierra                ES    2008   
20                                 Nigdy w zyciu!                PL    2004   
21                                     Nightwatch                US    1998   
22                                         Océans        FR, ES, CH    2009   
23                  Se souvenir des belles choses                FR    2002   
24                                     The Grudge            US, CA    2020   
25                                Vizontele Tuuba                TR    2004   

    tickets_sold_since_1996  tickets_sold  \
0                    803485        794169   
1                    850000        850000   
2                   2181416       1979965   
3                   1104115       1097403   
4                   1289438       1284597   
5                   1085680       1083857   
6                   1024895       1015418   
7                   1785984       1774437   
8                   1281613       1270356   
9                   1851505       1278403   
10                   754157        646335   
11                  1498599       1277427   
12                   517359        512323   
13                  2540016       2539916   
14                  1179378       1179378   
15                   553587        552121   
16                  1735658       1735658   
17                   961647        961584   
18                  1063747        992225   
19                  1364053       1363275   
20                  1623935       1620307   
21                   755241        665003   
22                  3993196       3930915   
23                   622360        584005   
24                  1347796       1347796   
25                  3249291       3249282   

                                    title_merge  year_plus  year_minus  \
0                                  african cats       2012        2010   
1                                    agir roman       1999        1997   
2                         de lautre cote du lit       2010        2008   
3               die wilden huhner und die liebe       2008        2006   
4                             die wilden huhner       2007        2005   
5               die wilden huhner und das leben       2010        2008   
6                                      drogowka       2014        2012   
7                               eddie the eagle       2017        2015   
8                           

ok year +/- 1 on original title is like 85 movies. Let's implement that into the function and check the result.

In [87]:
def double_merge_func(ticket_data, base_data = imdb_df):
    '''
    Merges our Tickets Sold Dataframes First on the newly created original title than second on the primary title.
    Afterward, merge again but with year +/- one. 

    Input:
        ticket_data ... either eu or na depending on what we are testing
        base_data = imdb_df

    Output:
        Returns: Dataframe with all matches from both columns
        Prints: Unmatched rows
    '''
    # first merge
    check_df = pd.merge(ticket_data,base_data, how="left", left_on=["title_merge", "year"], right_on=["original_title_merge", "year"])

    # set-up second df for further calculations
    check_mask = check_df["tconst"].isnull()
    second_merge_df = check_df[check_mask].copy()

    # drop columns from first merge
    second_merge_df.drop(columns = second_merge_df.iloc[:,6:], inplace=True)

    # second merge (inner)
    second_merge_df = second_merge_df.merge(base_data, how="inner", left_on=["title_merge", "year"], right_on=["primary_title_merge", "year"])

    # drop columns from first merge table that matched on second merge
    second_merge_mask = check_df["title"].isin(list(second_merge_df["title"]))
    check_df.drop(check_df[second_merge_mask].index, inplace=True)

    # add fitting rows from second merge to first table
    check_df = pd.concat([check_df, second_merge_df])
    check_df.reset_index(drop=True, inplace=True)

    # --- TIME FOR YEAR +/-1
    # set-up third df for further calculations
    check_mask = check_df["tconst"].isnull()
    third_merge_df = check_df[check_mask].copy()

    # drop columns from first merge
    third_merge_df.drop(columns = third_merge_df.iloc[:,6:], inplace=True)

    # add year plus and minus
    third_merge_df["year_plus"] = third_merge_df["year"] + 1
    third_merge_df["year_minus"] = third_merge_df["year"] - 1
    
    # 3_plus merge (inner)
    third_merge_plus_df = third_merge_df.merge(base_data, how="inner", left_on=["title_merge", "year_plus"], right_on=["original_title_merge", "year"])
    # drop columns from first merge table that matched on 3_plus merge (inner)
    third_merge_plus_mask = check_df["title"].isin(list(third_merge_plus_df["title"]))
    check_df.drop(check_df[third_merge_plus_mask].index, inplace=True)
    # add fitting rows from 3_plus merge (inner) to first table
    check_df = pd.concat([check_df, third_merge_plus_df])
    check_df.reset_index(drop=True, inplace=True)

    # 3_minus merge (inner)
    third_merge_minus_df = third_merge_df.merge(base_data, how="inner", left_on=["title_merge", "year_minus"], right_on=["original_title_merge", "year"])
    # drop columns from first merge table that matched on 3_minus merge (inner)
    third_merge_minus_mask = check_df["title"].isin(list(third_merge_minus_df["title"]))
    check_df.drop(check_df[third_merge_minus_mask].index, inplace=True)
    # add fitting rows from 3_plus merge (inner) to first table
    check_df = pd.concat([check_df, third_merge_minus_df])
    check_df.reset_index(drop=True, inplace=True)

    # -- Now do the same for PRIMARY TITLE ....
    # 3_plus merge (inner)
    third_merge_plus_df = third_merge_df.merge(base_data, how="inner", left_on=["title_merge", "year_plus"], right_on=["primary_title_merge", "year"])
    # drop columns from first merge table that matched on 3_plus merge (inner)
    third_merge_plus_mask = check_df["title"].isin(list(third_merge_plus_df["title"]))
    check_df.drop(check_df[third_merge_plus_mask].index, inplace=True)
    # add fitting rows from 3_plus merge (inner) to first table
    check_df = pd.concat([check_df, third_merge_plus_df])
    check_df.reset_index(drop=True, inplace=True)

    # 3_minus merge (inner)
    third_merge_minus_df = third_merge_df.merge(base_data, how="inner", left_on=["title_merge", "year_minus"], right_on=["primary_title_merge", "year"])
    # drop columns from first merge table that matched on 3_minus merge (inner)
    third_merge_minus_mask = check_df["title"].isin(list(third_merge_minus_df["title"]))
    check_df.drop(check_df[third_merge_minus_mask].index, inplace=True)
    # add fitting rows from 3_plus merge (inner) to first table
    check_df = pd.concat([check_df, third_merge_minus_df])
    check_df.reset_index(drop=True, inplace=True)

    # drop new year columns from final table
    check_df.drop(columns = check_df.iloc[:,-4:], inplace=True)

    # show unmatched rows
    check_mask = check_df["tconst"].isnull()
    display(check_df[check_mask])
    
    return check_df

In [88]:
eu_check_df = double_merge_func(eu_df)

title producing_country  \
223                                      American Pie 4                US   
258                                         Angry Birds            US, FI   
259             Angus, Thongs and Full-Frontal Snogging     GBinc, US, DE   
265                                         Annabelle 2                US   
299                 Arthur et la guerre des deux mondes                FR   
...                                                 ...               ...   
4251  Warum Männer nicht zuhören und Frauen schlecht...                DE   
4306           Winx club - Il segreto del regno perduto                IT   
4369                                        Zeny v behu                CZ   
4385                                            [Rec] 2                ES   
4412                                         Świadectwo                PL   

        year  tickets_sold_since_1996  tickets_sold  \
223   2012.0                 12501353      12500536   
258   2016.0                 10228756      10217533   
259   2008.0                  1358397       1346801   
265   2017.0                  7298882       7291919   
299   2010.0                  3838378       3363498   
...      ...                      ...           ...   
4251  2007.0                  1452342       1068475   
4306  2007.0                  2217926       2132336   
4369  2019.0                  1705959       1675569   
4385  2009.0                  1387671       1013091   
4412  2008.0                  1039901       1034911   

                                            title_merge tconst primary_title  \
223                                      american pie 4    NaN           NaN   
258                                         angry birds    NaN           NaN   
259               angus thongs and fullfrontal snogging    NaN           NaN   
265                                         annabelle 2    NaN           NaN   
299                 arthur et la guerre des deux mondes    NaN           NaN   
...                                                 ...    ...           ...   
4251  warum manner nicht zuhoren und frauen schlecht...    NaN           NaN   
4306            winx club  il segreto del regno perduto    NaN           NaN   
4369                                        zeny v behu    NaN           NaN   
4385                                              rec 2    NaN           NaN   
4412                                         swiadectwo    NaN           NaN   

     original_title runtime  ...  director_name  director2_name  \
223             NaN     NaN  ...            NaN             NaN   
258             NaN     NaN  ...            NaN             NaN   
259             NaN     NaN  ...            NaN             NaN   
265             NaN     NaN  ...            NaN             NaN   
299             NaN     NaN  ...            NaN             NaN   
...             ...     ...  ...            ...             ...   
4251            NaN     NaN  ...            NaN             NaN   
4306            NaN     NaN  ...            NaN             NaN   
4369            NaN     NaN  ...            NaN             NaN   
4385            NaN     NaN  ...            NaN             NaN   
4412            NaN     NaN  ...            NaN             NaN   

      director3_name writers_count writer_name writer2_name writer3_name  \
223              NaN           NaN         NaN          NaN          NaN   
258              NaN           NaN         NaN          NaN          NaN   
259              NaN           NaN         NaN          NaN          NaN   
265              NaN           NaN         NaN          NaN          NaN   
299              NaN           NaN         NaN          NaN          NaN   
...              ...           ...         ...          ...          ...   
4251             NaN           NaN         NaN          NaN          NaN   
4306             NaN           NaN         NaN          NaN          NaN   
4369          

We went from 255 to 169 with this new function! That is an improvement of 86!

### Let's check for the next shit

In [89]:
imdb_df[imdb_df["tconst"] == "tt0149601"]

tconst   primary_title original_title  year runtime  num_votes  \
3080  tt0149601  Cholera Street     Agir Roman  1997     120    11994.0   

      average_rating  genres_count  genre genre2  ...      director_name  \
3080             7.6           3.0  Crime  Drama  ...  Mustafa Altioklar   

     director2_name director3_name writers_count        writer_name  \
3080           None           None           2.0  Mustafa Altioklar   

     writer2_name  writer3_name is_adult original_title_merge  \
3080  Metin Kaçan          None        0           agir roman   

     primary_title_merge  
3080      cholera street  

[1 rows x 27 columns]

In [90]:
basic_df[basic_df["tconst"] == "tt0149601"]

tconst titleType    primaryTitle originalTitle  isAdult  startYear  \
145007  tt0149601     movie  Cholera Street    Agir Roman      0.0     1997.0   

       endYear runtimeMinutes               genres  
145007      \N            120  Crime,Drama,Romance

In [91]:
# let's delete basic_df again to have less huge variables loaded
del basic_df

In [92]:
eu_check_df[(eu_check_df["tconst"].isnull() ) & (eu_check_df["year"]==1998)]

title producing_country  \
776                              Crna mačka, beli mačor        FR, DE, YU   
784                                          Cumhuriyet                TR   
800   Dangerous Beauty (The Honest Courtesan, A Dest...                US   
1077                                        Elisabeth I                GB   
2319            Martha, Meet Frank, Daniel and Laurence                GB   
2840       Pokémon the First Movie: Mewtwo Strikes Back            JP, US   
3178                               Sibirskij tsiryulnik    RU, FR, IT, CZ   

        year  tickets_sold_since_1996  tickets_sold  \
776   1998.0                  2494989       2170497   
784   1998.0                   726000        726000   
800   1998.0                   929520        928888   
1077  1998.0                  3569152       3567062   
2319  1998.0                   666543        499834   
2840  1998.0                 12682197      12207823   
3178  1998.0                  1485657       1209107   

                                            title_merge tconst primary_title  \
776                               crna macka beli macor    NaN           NaN   
784                                          cumhuriyet    NaN           NaN   
800   dangerous beauty the honest courtesan a destin...    NaN           NaN   
1077                                        elisabeth i    NaN           NaN   
2319              martha meet frank daniel and laurence    NaN           NaN   
2840        pokemon the first movie mewtwo strikes back    NaN           NaN   
3178                               sibirskij tsiryulnik    NaN           NaN   

     original_title runtime  ...  director_name  director2_name  \
776             NaN     NaN  ...            NaN             NaN   
784             NaN     NaN  ...            NaN             NaN   
800             NaN     NaN  ...            NaN             NaN   
1077            NaN     NaN  ...            NaN             NaN   
2319            NaN     NaN  ...            NaN             NaN   
2840            NaN     NaN  ...            NaN             NaN   
3178            NaN     NaN  ...            NaN             NaN   

      director3_name writers_count writer_name writer2_name writer3_name  \
776              NaN           NaN         NaN          NaN          NaN   
784              NaN           NaN         NaN          NaN          NaN   
800              NaN           NaN         NaN          NaN          NaN   
1077             NaN           NaN         NaN          NaN          NaN   
2319             NaN           NaN         NaN          NaN          NaN   
2840             NaN           NaN         NaN          NaN          NaN   
3178             NaN           NaN         NaN          NaN          NaN   

     is_adult original_title_merge primary_title_merge  
776       NaN                  NaN                 NaN  
784       NaN                  NaN                 NaN  
800       NaN                  NaN                 NaN  
1077      NaN                  NaN                 NaN  
2319      NaN                  NaN                 NaN  
2840      NaN                  NaN                 NaN  
3178      NaN                  NaN                 NaN  

[7 rows x 32 columns]

placeholder: check if 11  - 1998 movies match if we change the filter and apply the year +-1 again

-> Gian-Luca on his branch

-> -> Done: Only got rid of 4 more movies sadly :( 

In [93]:
imdb_df[imdb_df["tconst"] == "tt1605630"]

tconst     primary_title    original_title  year runtime  num_votes  \
81655  tt1605630  American Reunion  American Reunion  2012     113   225651.0   

       average_rating  genres_count   genre genre2  ... director_name  \
81655             6.7           1.0  Comedy   None  ...   Jon Hurwitz   

           director2_name director3_name writers_count  writer_name  \
81655  Hayden Schlossberg           None           3.0  Jon Hurwitz   

             writer2_name  writer3_name is_adult original_title_merge  \
81655  Hayden Schlossberg     Adam Herz        0     american reunion   

      primary_title_merge  
81655    american reunion  

[1 rows x 27 columns]

### Import newly created AKAs_df

In [94]:
aka_query = f'''   SELECT *
                    FROM {schema}."imdb_akas_data"
                    '''

In [95]:
aka_df = sqlf.get_dataframe(aka_query)
display(aka_df.head())
aka_df.shape

tconst                          DE                       ES  \
0  tt0013274                        None                     None   
1  tt0015414                        None   La tierra de los toros   
2  tt0035423            Kate und Leopold     La Kate i en Leopold   
3  tt0062336                        None                     None   
4  tt0069049  The Other Side of the Wind  Al otro lado del viento   

                                          FR  \
0               Histoire de la guerre civile   
1                      La terre des taureaux   
2                            Kate et Léopold   
3  El Tango del Viudo y Su Espejo Deformante   
4                    De l'autre côté du vent   

                                                  GB  \
0                                               None   
1                                               None   
2                                     Kate & Leopold   
3  The Tango of the Widower and Its Distorting Mi...   
4                         The Other Side of the Wind   

                         IT    NL                   PL           TR  
0                      None  None                 None         None  
1                      None  None                 None         None  
2          Kate and Leopold  None       Kate i Leopold  Büyülü çift  
3                      None  None                 None         None  
4  L'altra faccia del vento  None  Druga strona wiatru         None

(112431, 9)

### Transform all titles accordingly
- lower
- unidecode
- remove punctuation

In [116]:
for column in aka_df.iloc[:,1:]:
    aka_df.loc[:,column] = aka_df[column].str.lower()
    aka_df.loc[:,column] = aka_df[column].astype(str).apply(unidecode)
    aka_df.loc[:,column] = aka_df.loc[:,column].str.translate(str.maketrans("","",string.punctuation))

In [117]:
aka_df.head()

tconst                          DE                       ES  \
0  tt0013274                        none                     none   
1  tt0015414                        none   la tierra de los toros   
2  tt0035423            kate und leopold     la kate i en leopold   
3  tt0062336                        none                     none   
4  tt0069049  the other side of the wind  al otro lado del viento   

                                          FR  \
0               histoire de la guerre civile   
1                      la terre des taureaux   
2                            kate et leopold   
3  el tango del viudo y su espejo deformante   
4                     de lautre cote du vent   

                                                  GB                       IT  \
0                                               none                     none   
1                                               none                     none   
2                                      kate  leopold         kate and leopold   
3  the tango of the widower and its distorting mi...                     none   
4                         the other side of the wind  laltra faccia del vento   

     NL                   PL           TR  
0  none                 none         none  
1  none                 none         none  
2  none       kate i leopold  buyulu cift  
3  none                 none         none  
4  none  druga strona wiatru         none

In [124]:
imdb_aka_df = pd.merge(imdb_df, aka_df, how="outer", on="tconst")

In [125]:
display(imdb_aka_df.shape)
imdb_df.shape

(188163, 35)

(188163, 27)

In [126]:
imdb_aka_df.head()

tconst                                      primary_title  \
0  tt0013274                        Istoriya grazhdanskoy voyny   
1  tt0015414                             La tierra de los toros   
2  tt0035423                                     Kate & Leopold   
3  tt0062336  The Tango of the Widower and Its Distorting Mi...   
4  tt0069049                         The Other Side of the Wind   

                              original_title  year runtime  num_votes  \
0                Istoriya grazhdanskoy voyny  2021      94       73.0   
1                     La tierra de los toros  2000      60       17.0   
2                             Kate & Leopold  2001     118    89944.0   
3  El tango del viudo y su espejo deformante  2020      70      190.0   
4                 The Other Side of the Wind  2018     122     8143.0   

   average_rating  genres_count        genre   genre2  ...  \
0             6.7           1.0  Documentary     None  ...   
1             5.4           NaN         None     None  ...   
2             6.4           3.0       Comedy  Fantasy  ...   
3             6.5           1.0        Drama     None  ...   
4             6.7           1.0        Drama     None  ...   

                        original_title_merge  \
0                istoriya grazhdanskoy voyny   
1                     la tierra de los toros   
2                              kate  leopold   
3  el tango del viudo y su espejo deformante   
4                 the other side of the wind   

                                 primary_title_merge  \
0                        istoriya grazhdanskoy voyny   
1                             la tierra de los toros   
2                                      kate  leopold   
3  the tango of the widower and its distorting mi...   
4                         the other side of the wind   

                           DE                       ES  \
0                        none                     none   
1                        none   la tierra de los toros   
2            kate und leopold     la kate i en leopold   
3                        none                     none   
4  the other side of the wind  al otro lado del viento   

                                          FR  \
0               histoire de la guerre civile   
1                      la terre des taureaux   
2                            kate et leopold   
3  el tango del viudo y su espejo deformante   
4                     de lautre cote du vent   

                                                  GB                       IT  \
0                                               none                     none   
1                                               none                     none   
2                                      kate  leopold         kate and leopold   
3  the tango of the widower and its distorting mi...                     none   
4                         the other side of the wind  laltra faccia del vento   

     NL                   PL           TR  
0  none                 none         none  
1  none                 none         none  
2  none       kate i leopold  buyulu cift  
3  none                 none         none  
4  none  druga strona wiatru         none  

[5 rows x 35 columns]

In [127]:
imdb_aka_df.columns

Index(['tconst', 'primary_title', 'original_title', 'year', 'runtime',
       'num_votes', 'average_rating', 'genres_count', 'genre', 'genre2',
       'genre3', 'acting', 'acting2', 'acting3', 'acting4', 'acting5',
       'directors_count', 'director_name', 'director2_name', 'director3_name',
       'writers_count', 'writer_name', 'writer2_name', 'writer3_name',
       'is_adult', 'original_title_merge', 'primary_title_merge', 'DE', 'ES',
       'FR', 'GB', 'IT', 'NL', 'PL', 'TR'],
      dtype='object')

### write the mother of all functions:
- goes over each title (original, primary, ...)
- for each title check merge with year and year +/-/1
- after the first merge, do the following merges on unmatched only and replace if neccassary

In [129]:
eu_df.head()

title producing_country  year  \
0                               (500) Days of Summer                US  2009   
1                                       (Nie)znajomi                PL  2019   
2                 (T)Raumschiff Surprise - Periode 1                DE  2004   
3  1 1/2 Ritter - Auf der Suche nach der hinreiße...                DE  2008   
4                                     1 chance sur 2                FR  1998   

   tickets_sold_since_1996  tickets_sold  \
0                  1713086       1684771   
1                   685075        684833   
2                 10763531      10731881   
3                  1986168       1986168   
4                  1295620       1238175   

                                         title_merge  
0                                 500 days of summer  
1                                         nieznajomi  
2                    traumschiff surprise  periode 1  
3  1 12 ritter  auf der suche nach der hinreissen...  
4                                     1 chance sur 2

In [131]:
imdb_aka_df.shape

(188163, 35)

In [165]:
def ultimate_merge_func(ticket_data, base_data = imdb_aka_df):
    '''
    Merges our Tickets Sold Dataframes First on each title for year and year +/- 1

    Input:
        ticket_data ... either eu or na depending on what we are testing
        base_data = imdb_df

    Output:
        Returns: Dataframe with all matches from both columns
        Prints: Unmatched rows
    '''

    list_titles = ['original_title_merge', 'primary_title_merge', 'DE', 'ES', 'FR', 'GB', 'IT', 'NL', 'PL', 'TR']
    counter = 0

    base_data["year_plus"] = base_data["year"] + 1
    base_data["year_minus"] = base_data["year"] + -1

    list_years = ["year_minus", "year", "year_plus"]

    for title in list_titles:
        if counter == 0:
            check_df = pd.merge(ticket_data,base_data, how="left", left_on=["title_merge", "year"], right_on=[title, "year"])

            
            # set-up third df for further calculations
            check_mask = check_df["tconst"].isnull()
            third_merge_df = check_df[check_mask].copy()

            # drop columns from first merge
            third_merge_df.drop(columns = third_merge_df.iloc[:,6:], inplace=True)
            
            # 3_plus merge (inner)
            third_merge_plus_df = third_merge_df.merge(base_data, how="inner", left_on=["title_merge", "year"], right_on=[title, "year_plus"])
            # drop columns from first merge table that matched on 3_plus merge (inner)
            third_merge_plus_mask = check_df["title"].isin(list(third_merge_plus_df["title"]))
            check_df.drop(check_df[third_merge_plus_mask].index, inplace=True)
            # add fitting rows from 3_plus merge (inner) to first table
            check_df = pd.concat([check_df, third_merge_plus_df])
            check_df.reset_index(drop=True, inplace=True)
            check_df.drop(columns = "year_x", inplace=True)

            # 3_minus merge (inner)
            third_merge_minus_df = third_merge_df.merge(base_data, how="inner", left_on=["title_merge", "year"], right_on=[title, "year_minus"])
            # drop columns from first merge table that matched on 3_minus merge (inner)
            third_merge_minus_mask = check_df["title"].isin(list(third_merge_minus_df["title"]))
            check_df.drop(check_df[third_merge_minus_mask].index, inplace=True)
            # add fitting rows from 3_plus merge (inner) to first table
            check_df = pd.concat([check_df, third_merge_minus_df])
            check_df.reset_index(drop=True, inplace=True)
            check_df.drop(columns = "year_x", inplace=True)

            counter += 1

        for year in list_years:
            # set-up third df for further calculations
            check_mask = check_df["tconst"].isnull()
            third_merge_df = check_df[check_mask].copy()

            # drop columns from first merge
            third_merge_df.drop(columns = third_merge_df.iloc[:,6:], inplace=True)
            
            # merge again
            third_merge_plus_df = third_merge_df.merge(base_data, how="inner", left_on=["title_merge", "year"], right_on=[title, year])
            # drop columns from first merge table that matched on 3_plus merge (inner)
            third_merge_plus_mask = check_df["title"].isin(list(third_merge_plus_df["title"]))
            check_df.drop(check_df[third_merge_plus_mask].index, inplace=True)
            # add fitting rows from 3_plus merge (inner) to first table
            check_df = pd.concat([check_df, third_merge_plus_df])
            check_df.reset_index(drop=True, inplace=True)
        counter += 1

    # drop new year columns from final table
    check_df.drop(columns = check_df.iloc[:,-4:], inplace=True)

    # show unmatched rows
    check_mask = check_df["tconst"].isnull()
    display(check_df[check_mask])
    display(counter)
    
    return check_df

In [166]:
test = ultimate_merge_func(eu_df)

title   producing_country  \
295                 Arthur et la guerre des deux mondes                  FR   
298                         Artificial Intelligence: AI                  US   
314          Astérix & Obélix: Au service de sa Majesté  FR, ES, IT, LT, BE   
317             Astérix: Le secret de la potion magique              FR, BE   
320                                 Atatürk 1881 - 1919                  TR   
...                                                 ...                 ...   
4189  Warum Männer nicht zuhören und Frauen schlecht...                  DE   
4244           Winx club - Il segreto del regno perduto                  IT   
4307                                        Zeny v behu                  CZ   
4323                                            [Rec] 2                  ES   
4350                                         Świadectwo                  PL   

        year  tickets_sold_since_1996  tickets_sold  \
295   2010.0                  3838378       3363498   
298   2001.0                  8073605       8041431   
314   2012.0                  6405518       6148156   
317   2018.0                  6513544       6499739   
320   2023.0                  1732649       1732649   
...      ...                      ...           ...   
4189  2007.0                  1452342       1068475   
4244  2007.0                  2217926       2132336   
4307  2019.0                  1705959       1675569   
4323  2009.0                  1387671       1013091   
4350  2008.0                  1039901       1034911   

                                            title_merge tconst primary_title  \
295                 arthur et la guerre des deux mondes    NaN           NaN   
298                          artificial intelligence ai    NaN           NaN   
314            asterix  obelix au service de sa majeste    NaN           NaN   
317              asterix le secret de la potion magique    NaN           NaN   
320                                  ataturk 1881  1919    NaN           NaN   
...                                                 ...    ...           ...   
4189  warum manner nicht zuhoren und frauen schlecht...    NaN           NaN   
4244            winx club  il segreto del regno perduto    NaN           NaN   
4307                                        zeny v behu    NaN           NaN   
4323                                              rec 2    NaN           NaN   
4350                                         swiadectwo    NaN           NaN   

     original_title runtime  ...  original_title_merge  primary_title_merge  \
295             NaN     NaN  ...                   NaN                  NaN   
298             NaN     NaN  ...                   NaN                  NaN   
314             NaN     NaN  ...                   NaN                  NaN   
317             NaN     NaN  ...                   NaN                  NaN   
320             NaN     NaN  ...                   NaN                  NaN   
...             ...     ...  ...                   ...                  ...   
4189            NaN     NaN  ...                   NaN                  NaN   
4244            NaN     NaN  ...                   NaN                  NaN   
4307            NaN     NaN  ...                   NaN                  NaN   
4323            NaN     NaN  ...                   NaN                  NaN   
4350            NaN     NaN  ...                   NaN                  NaN   

       DE   ES   FR   GB   IT   NL   PL   TR  
295   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
298   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
314   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
317   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
320   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
...   ...  ...  ...  ...  ...  ...  ...  ...  
4189  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4244  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4307  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4323  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4350  NaN  Na

11

Ok, After applying the MOTHER OF ALL FUNCTIONS using the AKAs titles reduces the number of unmatched rows down to 103 (from 169).
That is an improvement of 66 rows

### Let's Check again what else we could do